<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>权大师测试报告,详细信息请查看附件</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    
<style type="text/css" media="screen">
body        { font-family: Microsoft YaHei,Tahoma,arial,helvetica,sans-serif;padding: 20px; font-size: 80%; }
table       { font-size: 100%; }

/* -- heading ---------------------------------------------------------------------- */
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}

.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}

/* -- report ------------------------------------------------------------------------ */
#total_row  { font-weight: bold; }
.passCase   { color: #5cb85c; }
.failCase   { color: #d9534f; font-weight: bold; }
.errorCase  { color: #f0ad4e; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }
</style>

</head>
<body >
<script language="javascript" type="text/javascript">
output_list = Array();

/*level 调整增加只显示通过用例的分类 --Findyou
0:Summary //all hiddenRow
1:Failed  //pt hiddenRow, ft none
2:Pass    //pt none, ft hiddenRow
3:All     //pt none, ft none
*/
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level == 2 || level == 0 ) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level < 2) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
    }

    //加入【详细】切换文字变化 --Findyou
    detail_class=document.getElementsByClassName('detail');
	//console.log(detail_class.length)
	if (level == 3) {
		for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="收起"
		}
	}
	else{
			for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="详细"
		}
	}
}

function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        //ID修改 点 为 下划线 -Findyou
        tid0 = 't' + cid.substr(1) + '_' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        //修改点击无法收起的BUG，加入【详细】切换文字变化 --Findyou
        if (toHide) {
            document.getElementById(tid).className = 'hiddenRow';
            document.getElementById(cid).innerText = "详细"
        }
        else {
            document.getElementById(tid).className = '';
            document.getElementById(cid).innerText = "收起"
        }
    }
}

function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}
</script>
<div class='heading'>
<h1 style="font-family: Microsoft YaHei">权大师测试报告,详细信息请查看附件</h1>
<p class='attribute'><strong>测试人员 : </strong> lijiawei</p>
<p class='attribute'><strong>开始时间 : </strong> 2018-09-04 22:00:05</p>
<p class='attribute'><strong>合计耗时 : </strong> 1:10:47.854218</p>
<p class='attribute'><strong>测试结果 : </strong> 共 86，通过 4，错误 82，通过率= 4.65%</p>

<p class='description'>Environment:  OS:win10  Browser:chrome</p>
</div>



<p id='show_detail_line'>
<a class="btn btn-primary" href='javascript:showCase(0)'>概要{ 4.65% }</a>
<a class="btn btn-danger" href='javascript:showCase(1)'>失败{ 0 }</a>
<a class="btn btn-success" href='javascript:showCase(2)'>通过{ 4 }</a>
<a class="btn btn-info" href='javascript:showCase(3)'>所有{ 86 }</a>
</p>
<table id='result_table' class="table table-condensed table-bordered table-hover">
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row' class="text-center success" style="font-weight: bold;font-size: 14px;">
    <td>用例集/测试用例</td>
    <td>总计</td>
    <td>通过</td>
    <td>失败</td>
    <td>错误</td>
    <td>详细</td>
</tr>

<tr class='errorClass warning'>
    <td>bmkstest.BmKsTest: 保姆注册测试集</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">1</td>
    <td class="text-center"><a href="javascript:showClassDetail('c1',1)" class="detail" id='c1'>详细</a></td>
</tr>

<tr id='ft1_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_bmks: 保姆快速注册</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_1'>错误</button>
    <div id='div_ft1_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_1'>错误</button>
    <div id='div_ft1_1' class="collapse in">
    <pre>
    
ft1_1: 2018-09-04 22:00:05,750 - root - INFO - ############################### START ###############################
保姆快速注册-权大师
费用总计:600.00
2018-09-04 22:00:38,051 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\bmkstest.py", line 70, in test_bmks
    self.driver.find_element_by_name("ownerContactPerson").send_keys("全大师")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 365, in find_element_by_name
    return self.find_element(by=By.NAME, value=name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: None
Message: unexpected alert open: {Alert text : 请登录}
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>bqywtest.BqYwTest: 版权业务测试集</td>
    <td class="text-center">7</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">7</td>
    <td class="text-center"><a href="javascript:showClassDetail('c2',7)" class="detail" id='c2'>详细</a></td>
</tr>

<tr id='ft2_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_msdj: 美术作品版权登记加急测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_1'>错误</button>
    <div id='div_ft2_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_1'>错误</button>
    <div id='div_ft2_1' class="collapse in">
    <pre>
    
ft2_1: 2018-09-04 22:00:38,092 - root - INFO - ############################### START ###############################
2018-09-04 22:01:13,427 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\bqywtest.py", line 96, in test_msdj
    self.assertIn("美术作品版权登记加急-权大师",self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_mszp: 美术作品版权登记测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_2'>错误</button>
    <div id='div_ft2_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_2'>错误</button>
    <div id='div_ft2_2' class="collapse in">
    <pre>
    
ft2_2: 2018-09-04 22:01:13,474 - root - INFO - ############################### START ###############################
2018-09-04 22:02:15,758 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\bqywtest.py", line 39, in test_mszp
    self.assertIn("美术作品版权登记-权大师",self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_rjbg: 软件著作权变更测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_3'>错误</button>
    <div id='div_ft2_3' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_3'>错误</button>
    <div id='div_ft2_3' class="collapse in">
    <pre>
    
ft2_3: 2018-09-04 22:02:15,785 - root - INFO - ############################### START ###############################
2018-09-04 22:03:15,796 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\bqywtest.py", line 269, in test_rjbg
    self.assertIn("软件著作权变更-权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_4' class='none'>
    <td class='errorCase'><div class='testcase'>test_rjbz: 软件著作权补证测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_4'>错误</button>
    <div id='div_ft2_4' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_4'>错误</button>
    <div id='div_ft2_4' class="collapse in">
    <pre>
    
ft2_4: 2018-09-04 22:03:15,824 - root - INFO - ############################### START ###############################
2018-09-04 22:04:19,616 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\bqywtest.py", line 327, in test_rjbz
    self.assertIn("软件著作权补证-权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_5' class='none'>
    <td class='errorCase'><div class='testcase'>test_rjzr: 软件著作权转让测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_5'>错误</button>
    <div id='div_ft2_5' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_5'>错误</button>
    <div id='div_ft2_5' class="collapse in">
    <pre>
    
ft2_5: 2018-09-04 22:04:19,627 - root - INFO - ############################### START ###############################
2018-09-04 22:05:19,911 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\bqywtest.py", line 385, in test_rjzr
    self.assertIn("软件著作权转让-权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_6' class='none'>
    <td class='errorCase'><div class='testcase'>test_wzdj: 文字作品版权登记加急测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_6'>错误</button>
    <div id='div_ft2_6' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_6'>错误</button>
    <div id='div_ft2_6' class="collapse in">
    <pre>
    
ft2_6: 2018-09-04 22:05:19,928 - root - INFO - ############################### START ###############################
2018-09-04 22:06:23,266 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\bqywtest.py", line 210, in test_wzdj
    self.assertIn("文字作品版权登记加急-权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_7' class='none'>
    <td class='errorCase'><div class='testcase'>test_wzzp: 文字作品版权登记测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_7'>错误</button>
    <div id='div_ft2_7' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_7'>错误</button>
    <div id='div_ft2_7' class="collapse in">
    <pre>
    
ft2_7: 2018-09-04 22:06:23,276 - root - INFO - ############################### START ###############################
2018-09-04 22:07:25,948 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\bqywtest.py", line 153, in test_wzzp
    self.assertIn("文字作品版权登记-权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>cxzctest.CxZcTest: 查询注册测试集</td>
    <td class="text-center">2</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">1</td>
    <td class="text-center"><a href="javascript:showClassDetail('c3',2)" class="detail" id='c3'>详细</a></td>
</tr>

<tr id='ft3_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_gnsb: 国内商标查询测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_1'>错误</button>
    <div id='div_ft3_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_1'>错误</button>
    <div id='div_ft3_1' class="collapse in">
    <pre>
    
ft3_1: 2018-09-04 22:07:25,965 - root - INFO - ############################### START ###############################
国内商标查询（报告）-国内商标查询报告-权大师
费用总计:99.00
2018-09-04 22:07:56,753 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\cxzctest.py", line 78, in test_gnsb
    self.driver.find_element_by_name("ownerContactPerson").send_keys("全大师")
AttributeError: 'NoneType' object has no attribute 'send_keys'


    </pre>
    </div>
    </td>
</tr>

<tr id='pt3_2' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_mfsb: 免费商标查询测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt3_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt3_2'>通过</button>
    <div id='div_pt3_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt3_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt3_2'>通过</button>
    <div id='div_pt3_2' class="collapse in">
    <pre>
    
pt3_2: 2018-09-04 22:07:56,785 - root - INFO - ############################### START ###############################
注册商标查询_中国商标查询_权大师官网
2018-09-04 22:08:33,877 - root - INFO - ###############################  End  ###############################


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>dbwytest.DbWyTest: 担保无忧测试集</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">1</td>
    <td class="text-center"><a href="javascript:showClassDetail('c4',1)" class="detail" id='c4'>详细</a></td>
</tr>

<tr id='ft4_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_dbwy: 担保无忧测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_1'>错误</button>
    <div id='div_ft4_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_1'>错误</button>
    <div id='div_ft4_1' class="collapse in">
    <pre>
    
ft4_1: 2018-09-04 22:08:33,895 - root - INFO - ############################### START ###############################
担保无忧注册-权大师
费用总计:1280.00
2018-09-04 22:09:05,716 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\dbwytest.py", line 54, in test_dbwy
    self.driver.find_element_by_name("ownerContactPerson").send_keys("全大师")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 365, in find_element_by_name
    return self.find_element(by=By.NAME, value=name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: None
Message: unexpected alert open: {Alert text : 请登录}
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>fmzltest.FmZlTest: 发明专利测试集</td>
    <td class="text-center">6</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">6</td>
    <td class="text-center"><a href="javascript:showClassDetail('c5',6)" class="detail" id='c5'>详细</a></td>
</tr>

<tr id='ft5_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_fmzlbz_1: 标准型-单个申请人减缓</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_1'>错误</button>
    <div id='div_ft5_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_1'>错误</button>
    <div id='div_ft5_1' class="collapse in">
    <pre>
    
ft5_1: 2018-09-04 22:09:05,781 - root - INFO - ############################### START ###############################
2018-09-04 22:10:02,360 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\fmzltest.py", line 37, in test_fmzlbz_1
    self.assertIn("发明专利标准申请|专利申请|专利查询|权大师",self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_fmzlbz_2: 标准型-多个申请人减缓</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_2'>错误</button>
    <div id='div_ft5_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_2'>错误</button>
    <div id='div_ft5_2' class="collapse in">
    <pre>
    
ft5_2: 2018-09-04 22:10:02,384 - root - INFO - ############################### START ###############################
2018-09-04 22:11:02,936 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\fmzltest.py", line 101, in test_fmzlbz_2
    self.assertIn("发明专利标准申请|专利申请|专利查询|权大师",self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_fmzlbz_3: 标准型-不减缓</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_3'>错误</button>
    <div id='div_ft5_3' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_3'>错误</button>
    <div id='div_ft5_3' class="collapse in">
    <pre>
    
ft5_3: 2018-09-04 22:11:02,945 - root - INFO - ############################### START ###############################
2018-09-04 22:11:56,637 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\fmzltest.py", line 164, in test_fmzlbz_3
    self.assertIn("发明专利标准申请|专利申请|专利查询|权大师",self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_4' class='none'>
    <td class='errorCase'><div class='testcase'>test_fmzldb_1: 担保型-单个申请人减缓</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_4'>错误</button>
    <div id='div_ft5_4' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_4'>错误</button>
    <div id='div_ft5_4' class="collapse in">
    <pre>
    
ft5_4: 2018-09-04 22:11:56,663 - root - INFO - ############################### START ###############################
2018-09-04 22:12:50,445 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\fmzltest.py", line 226, in test_fmzldb_1
    self.assertIn("发明专利担保申请|专利申请|专利查询|权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_5' class='none'>
    <td class='errorCase'><div class='testcase'>test_fmzldb_2: 担保型-多个申请人减缓</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_5'>错误</button>
    <div id='div_ft5_5' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_5'>错误</button>
    <div id='div_ft5_5' class="collapse in">
    <pre>
    
ft5_5: 2018-09-04 22:12:50,463 - root - INFO - ############################### START ###############################
2018-09-04 22:13:43,731 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\fmzltest.py", line 289, in test_fmzldb_2
    self.assertIn("发明专利担保申请|专利申请|专利查询|权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_6' class='none'>
    <td class='errorCase'><div class='testcase'>test_fmzldb_3: 担保型-不减缓</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_6'>错误</button>
    <div id='div_ft5_6' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_6'>错误</button>
    <div id='div_ft5_6' class="collapse in">
    <pre>
    
ft5_6: 2018-09-04 22:13:43,739 - root - INFO - ############################### START ###############################
2018-09-04 22:14:38,334 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\fmzltest.py", line 352, in test_fmzldb_3
    self.assertIn("发明专利担保申请|专利申请|专利查询|权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>hhrtest.HhrTest: 合伙人个人中心测试集</td>
    <td class="text-center">3</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">3</td>
    <td class="text-center"><a href="javascript:showClassDetail('c6',3)" class="detail" id='c6'>详细</a></td>
</tr>

<tr id='ft6_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_hhrqdxd: 渠道下单单个商标注册</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft6_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft6_1'>错误</button>
    <div id='div_ft6_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft6_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft6_1'>错误</button>
    <div id='div_ft6_1' class="collapse in">
    <pre>
    
ft6_1: 2018-09-04 22:14:38,358 - root - INFO - ############################### START ###############################
2018-09-04 22:15:31,021 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\hhrtest.py", line 217, in test_hhrqdxd
    self.driver.find_element_by_xpath("//*[@id=\"personalCenter2-rightContainer\"]/div[1]/div/a").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="personalCenter2-rightContainer"]/div[1]/div/a"}
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft6_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_hhrsbzc: 合伙人商标注册</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft6_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft6_2'>错误</button>
    <div id='div_ft6_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft6_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft6_2'>错误</button>
    <div id='div_ft6_2' class="collapse in">
    <pre>
    
ft6_2: 2018-09-04 22:15:31,054 - root - INFO - ############################### START ###############################
2018-09-04 22:16:56,438 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\hhrtest.py", line 121, in test_hhrsbzc
    self.driver.find_element_by_xpath("//*[@id=\"personalCenter2-rightContainer\"]/div[1]/div/a").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="personalCenter2-rightContainer"]/div[1]/div/a"}
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft6_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_sbddxg: 商标订单</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft6_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft6_3'>错误</button>
    <div id='div_ft6_3' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft6_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft6_3'>错误</button>
    <div id='div_ft6_3' class="collapse in">
    <pre>
    
ft6_3: 2018-09-04 22:16:56,451 - root - INFO - ############################### START ###############################
2018-09-04 22:18:15,422 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\hhrtest.py", line 27, in test_sbddxg
    self.driver.find_element_by_xpath("//*[@id=\"personalCenter2-rightContainer\"]/div[1]/div/a").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="personalCenter2-rightContainer"]/div[1]/div/a"}
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>hometest.HomeTest: 个人中心测试集</td>
    <td class="text-center">4</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">4</td>
    <td class="text-center"><a href="javascript:showClassDetail('c7',4)" class="detail" id='c7'>详细</a></td>
</tr>

<tr id='ft7_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_ddzx: 订单中心</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft7_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft7_1'>错误</button>
    <div id='div_ft7_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft7_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft7_1'>错误</button>
    <div id='div_ft7_1' class="collapse in">
    <pre>
    
ft7_1: 2018-09-04 22:18:15,433 - root - INFO - ############################### START ###############################
2018-09-04 22:19:45,760 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\hometest.py", line 35, in test_ddzx
    self.driver.find_element_by_css_selector("#personalCenter2-leftNav &gt; ul &gt; li.menu.open &gt; ul &gt; li:nth-child(1) &gt; a").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 437, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#personalCenter2-leftNav &gt; ul &gt; li.menu.open &gt; ul &gt; li:nth-child(1) &gt; a"}
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft7_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_dzgl: 发票地址管理</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft7_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft7_2'>错误</button>
    <div id='div_ft7_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft7_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft7_2'>错误</button>
    <div id='div_ft7_2' class="collapse in">
    <pre>
    
ft7_2: 2018-09-04 22:19:45,827 - root - INFO - ############################### START ###############################
2018-09-04 22:21:08,868 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\hometest.py", line 124, in test_dzgl
    self.driver.find_element_by_link_text("邮寄地址管理").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 317, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"邮寄地址管理"}
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft7_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_fpsq: 发票申请</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft7_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft7_3'>错误</button>
    <div id='div_ft7_3' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft7_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft7_3'>错误</button>
    <div id='div_ft7_3' class="collapse in">
    <pre>
    
ft7_3: 2018-09-04 22:21:08,885 - root - INFO - ############################### START ###############################
2018-09-04 22:22:27,976 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\hometest.py", line 168, in test_fpsq
    self.driver.find_element_by_link_text("发票申请").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 317, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"发票申请"}
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft7_4' class='none'>
    <td class='errorCase'><div class='testcase'>test_gwyj: 官文邮寄</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft7_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft7_4'>错误</button>
    <div id='div_ft7_4' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft7_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft7_4'>错误</button>
    <div id='div_ft7_4' class="collapse in">
    <pre>
    
ft7_4: 2018-09-04 22:22:27,985 - root - INFO - ############################### START ###############################
2018-09-04 22:23:21,584 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\hometest.py", line 218, in test_gwyj
    self.driver.find_element_by_link_text("官文管理").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 317, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"官文管理"}
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>hwgstest.HwGsTest: 海外高速测试集</td>
    <td class="text-center">2</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">2</td>
    <td class="text-center"><a href="javascript:showClassDetail('c8',2)" class="detail" id='c8'>详细</a></td>
</tr>

<tr id='ft8_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_hwgs_1: 海外高速测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft8_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft8_1'>错误</button>
    <div id='div_ft8_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft8_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft8_1'>错误</button>
    <div id='div_ft8_1' class="collapse in">
    <pre>
    
ft8_1: 2018-09-04 22:23:21,597 - root - INFO - ############################### START ###############################
海外公司智能注册-权大师
费用总计:600.00
商标名称：fZelina
选择了第33类商标分类！
2018-09-04 22:24:57,593 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\hwgstest.py", line 99, in test_hwgs_1
    "body &gt; div.smartRegister-page &gt; div.agentInfo-wrap.applicant-wrap.overseas &gt; div.section-base &gt; div.overseas-form &gt; table.table-1.table-overseas.table-type2.active &gt; tbody.tbody-qiye &gt; tr:nth-child(1) &gt; td.td-content.contact-select-container &gt; dl &gt; dt &gt; input").send_keys(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 437, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"body &gt; div.smartRegister-page &gt; div.agentInfo-wrap.applicant-wrap.overseas &gt; div.section-base &gt; div.overseas-form &gt; table.table-1.table-overseas.table-type2.active &gt; tbody.tbody-qiye &gt; tr:nth-child(1) &gt; td.td-content.contact-select-container &gt; dl &gt; dt &gt; input"}
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft8_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_hwgs_2: 海外高速_自然人测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft8_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft8_2'>错误</button>
    <div id='div_ft8_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft8_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft8_2'>错误</button>
    <div id='div_ft8_2' class="collapse in">
    <pre>
    
ft8_2: 2018-09-04 22:24:57,623 - root - INFO - ############################### START ###############################
海外公司智能注册-权大师
费用总计:600.00
商标名称：两涕持猖鸡
选择了第28类商标分类！
2018-09-04 22:26:31,980 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\hwgstest.py", line 235, in test_hwgs_2
    self.driver.find_element_by_css_selector("body &gt; div.smartRegister-page &gt; div.agentInfo-wrap.applicant-wrap.overseas &gt; div.section-base &gt; table &gt; thead &gt; tr:nth-child(1) &gt; td.td-content &gt; a:nth-child(2)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 437, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"body &gt; div.smartRegister-page &gt; div.agentInfo-wrap.applicant-wrap.overseas &gt; div.section-base &gt; table &gt; thead &gt; tr:nth-child(1) &gt; td.td-content &gt; a:nth-child(2)"}
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>hwsctest.HwScTest: 海外市场测试集</td>
    <td class="text-center">6</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">6</td>
    <td class="text-center"><a href="javascript:showClassDetail('c9',6)" class="detail" id='c9'>详细</a></td>
</tr>

<tr id='ft9_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_mdl: 马德里商标注册测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft9_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft9_1'>错误</button>
    <div id='div_ft9_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft9_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft9_1'>错误</button>
    <div id='div_ft9_1' class="collapse in">
    <pre>
    
ft9_1: 2018-09-04 22:26:31,992 - root - INFO - ############################### START ###############################
马德里商标注册
费用总计:6600.00
2018-09-04 22:26:58,761 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\hwsctest.py", line 48, in test_mdl
    self.driver.find_element_by_name("ownerContactPerson").send_keys("全大师")
AttributeError: 'NoneType' object has no attribute 'send_keys'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft9_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_mg: 美国商标注册测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft9_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft9_2'>错误</button>
    <div id='div_ft9_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft9_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft9_2'>错误</button>
    <div id='div_ft9_2' class="collapse in">
    <pre>
    
ft9_2: 2018-09-04 22:26:58,789 - root - INFO - ############################### START ###############################
美国商标注册-权大师
费用总计:5799.00
2018-09-04 22:27:26,019 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\hwsctest.py", line 105, in test_mg
    self.driver.find_element_by_name("ownerContactPerson").send_keys("全大师")
AttributeError: 'NoneType' object has no attribute 'send_keys'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft9_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_om: 欧盟商标注册测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft9_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft9_3'>错误</button>
    <div id='div_ft9_3' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft9_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft9_3'>错误</button>
    <div id='div_ft9_3' class="collapse in">
    <pre>
    
ft9_3: 2018-09-04 22:27:26,026 - root - INFO - ############################### START ###############################
欧盟商标注册-权大师
费用总计:11499.00
2018-09-04 22:27:54,632 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\hwsctest.py", line 163, in test_om
    self.driver.find_element_by_name("ownerContactPerson").send_keys("全大师")
AttributeError: 'NoneType' object has no attribute 'send_keys'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft9_4' class='none'>
    <td class='errorCase'><div class='testcase'>test_rb: 日本商标注册测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft9_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft9_4'>错误</button>
    <div id='div_ft9_4' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft9_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft9_4'>错误</button>
    <div id='div_ft9_4' class="collapse in">
    <pre>
    
ft9_4: 2018-09-04 22:27:54,639 - root - INFO - ############################### START ###############################
日本商标注册-权大师
费用总计:6899.00
2018-09-04 22:28:21,504 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\hwsctest.py", line 221, in test_rb
    self.driver.find_element_by_name("ownerContactPerson").send_keys("全大师")
AttributeError: 'NoneType' object has no attribute 'send_keys'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft9_5' class='none'>
    <td class='errorCase'><div class='testcase'>test_xg: 香港商标注册测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft9_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft9_5'>错误</button>
    <div id='div_ft9_5' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft9_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft9_5'>错误</button>
    <div id='div_ft9_5' class="collapse in">
    <pre>
    
ft9_5: 2018-09-04 22:28:21,516 - root - INFO - ############################### START ###############################
香港商标注册-权大师
费用总计:3299.00
2018-09-04 22:28:51,653 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\hwsctest.py", line 336, in test_xg
    self.driver.find_element_by_name("ownerContactPerson").send_keys("全大师")
AttributeError: 'NoneType' object has no attribute 'send_keys'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft9_6' class='none'>
    <td class='errorCase'><div class='testcase'>test_yd: 印度商标注册测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft9_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft9_6'>错误</button>
    <div id='div_ft9_6' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft9_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft9_6'>错误</button>
    <div id='div_ft9_6' class="collapse in">
    <pre>
    
ft9_6: 2018-09-04 22:28:51,662 - root - INFO - ############################### START ###############################
印度商标注册-权大师
费用总计:4699.00
2018-09-04 22:29:19,698 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\hwsctest.py", line 279, in test_yd
    self.driver.find_element_by_name("ownerContactPerson").send_keys("全大师")
AttributeError: 'NoneType' object has no attribute 'send_keys'


    </pre>
    </div>
    </td>
</tr>

<tr class='passClass warning'>
    <td>mfsbtest.MfSbTest: 商标搜索查询测试集</td>
    <td class="text-center">1</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c10',1)" class="detail" id='c10'>详细</a></td>
</tr>

<tr id='pt10_1' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_sbss: 商标搜索</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt10_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt10_1'>通过</button>
    <div id='div_pt10_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt10_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt10_1'>通过</button>
    <div id='div_pt10_1' class="collapse in">
    <pre>
    
pt10_1: 2018-09-04 22:29:19,711 - root - INFO - ############################### START ###############################
注册商标查询_中国商标查询_权大师官网
搜索商标名称：fCressida
注册商标查询_中国商标查询_权大师官网
商标搜索测试通过
2018-09-04 22:29:48,687 - root - INFO - ###############################  End  ###############################


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>qtzltest.QtZlTest: 专利补充测试集</td>
    <td class="text-center">11</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">11</td>
    <td class="text-center"><a href="javascript:showClassDetail('c11',11)" class="detail" id='c11'>详细</a></td>
</tr>

<tr id='ft11_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_nfjn_2: 实用新型专利年费缴纳</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft11_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft11_1'>错误</button>
    <div id='div_ft11_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft11_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft11_1'>错误</button>
    <div id='div_ft11_1' class="collapse in">
    <pre>
    
ft11_1: 2018-09-04 22:29:48,697 - root - INFO - ############################### START ###############################
2018-09-04 22:30:43,401 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\qtzltest.py", line 384, in test_nfjn_2
    self.assertIn("发明专利年费缴纳-权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft11_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_nfjn_3: 产品外观设计专利年费缴纳</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft11_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft11_2'>错误</button>
    <div id='div_ft11_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft11_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft11_2'>错误</button>
    <div id='div_ft11_2' class="collapse in">
    <pre>
    
ft11_2: 2018-09-04 22:30:43,445 - root - INFO - ############################### START ###############################
2018-09-04 22:31:12,123 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\qtzltest.py", line 449, in test_nfjn_3
    self.assertIn("发明专利年费缴纳-权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft11_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_zlbg_2: 邮编地址变更测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft11_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft11_3'>错误</button>
    <div id='div_ft11_3' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft11_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft11_3'>错误</button>
    <div id='div_ft11_3' class="collapse in">
    <pre>
    
ft11_3: 2018-09-04 22:31:12,134 - root - INFO - ############################### START ###############################
2018-09-04 22:32:07,808 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\qtzltest.py", line 520, in test_zlbg_2
    self.assertIn("专利著录项变更-权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft11_4' class='none'>
    <td class='errorCase'><div class='testcase'>test_zlbg_3: 申请人变更测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft11_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft11_4'>错误</button>
    <div id='div_ft11_4' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft11_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft11_4'>错误</button>
    <div id='div_ft11_4' class="collapse in">
    <pre>
    
ft11_4: 2018-09-04 22:32:07,821 - root - INFO - ############################### START ###############################
2018-09-04 22:33:12,967 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\qtzltest.py", line 580, in test_zlbg_3
    self.assertIn("专利著录项变更-权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft11_5' class='none'>
    <td class='errorCase'><div class='testcase'>test_zlbg_4: 代理机构变更测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft11_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft11_5'>错误</button>
    <div id='div_ft11_5' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft11_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft11_5'>错误</button>
    <div id='div_ft11_5' class="collapse in">
    <pre>
    
ft11_5: 2018-09-04 22:33:12,976 - root - INFO - ############################### START ###############################
2018-09-04 22:34:06,968 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\qtzltest.py", line 640, in test_zlbg_4
    self.assertIn("专利著录项变更-权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft11_6' class='none'>
    <td class='errorCase'><div class='testcase'>test_zlbh_2: 实用新型专利驳回复审</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft11_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft11_6'>错误</button>
    <div id='div_ft11_6' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft11_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft11_6'>错误</button>
    <div id='div_ft11_6' class="collapse in">
    <pre>
    
ft11_6: 2018-09-04 22:34:06,978 - root - INFO - ############################### START ###############################
2018-09-04 22:35:03,520 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\qtzltest.py", line 35, in test_zlbh_2
    self.assertIn("发明专利驳回复审_权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft11_7' class='none'>
    <td class='errorCase'><div class='testcase'>test_zlbh_3: 产品外观设计专利驳回复审</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft11_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft11_7'>错误</button>
    <div id='div_ft11_7' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft11_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft11_7'>错误</button>
    <div id='div_ft11_7' class="collapse in">
    <pre>
    
ft11_7: 2018-09-04 22:35:03,545 - root - INFO - ############################### START ###############################
2018-09-04 22:36:02,727 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\qtzltest.py", line 93, in test_zlbh_3
    self.assertIn("发明专利驳回复审_权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft11_8' class='none'>
    <td class='errorCase'><div class='testcase'>test_zldb_2: 发明专利无效答辩测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft11_8' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft11_8'>错误</button>
    <div id='div_ft11_8' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft11_8' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft11_8'>错误</button>
    <div id='div_ft11_8' class="collapse in">
    <pre>
    
ft11_8: 2018-09-04 22:36:02,757 - root - INFO - ############################### START ###############################
2018-09-04 22:36:58,202 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\qtzltest.py", line 269, in test_zldb_2
    self.assertIn("发明专利无效答辩_权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft11_9' class='none'>
    <td class='errorCase'><div class='testcase'>test_zldb_3: 发明专利无效答辩测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft11_9' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft11_9'>错误</button>
    <div id='div_ft11_9' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft11_9' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft11_9'>错误</button>
    <div id='div_ft11_9' class="collapse in">
    <pre>
    
ft11_9: 2018-09-04 22:36:58,227 - root - INFO - ############################### START ###############################
2018-09-04 22:37:30,560 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\qtzltest.py", line 326, in test_zldb_3
    self.assertIn("发明专利无效答辩_权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft11_10' class='none'>
    <td class='errorCase'><div class='testcase'>test_zlxg_2: 实用新型专利无效宣告</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft11_10' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft11_10'>错误</button>
    <div id='div_ft11_10' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft11_10' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft11_10'>错误</button>
    <div id='div_ft11_10' class="collapse in">
    <pre>
    
ft11_10: 2018-09-04 22:37:30,572 - root - INFO - ############################### START ###############################
2018-09-04 22:38:25,203 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\qtzltest.py", line 152, in test_zlxg_2
    self.assertIn("专利无效宣告_权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft11_11' class='none'>
    <td class='errorCase'><div class='testcase'>test_zlxg_3: 产品外观设计专利无效宣告</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft11_11' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft11_11'>错误</button>
    <div id='div_ft11_11' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft11_11' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft11_11'>错误</button>
    <div id='div_ft11_11' class="collapse in">
    <pre>
    
ft11_11: 2018-09-04 22:38:25,233 - root - INFO - ############################### START ###############################
2018-09-04 22:38:52,333 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\qtzltest.py", line 211, in test_zlxg_3
    self.assertIn("专利无效宣告_权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>rjzztest.RjZzTest: 软件著作权测试集</td>
    <td class="text-center">2</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">2</td>
    <td class="text-center"><a href="javascript:showClassDetail('c12',2)" class="detail" id='c12'>详细</a></td>
</tr>

<tr id='ft12_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_rjzz: 软件著作权登记加急</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft12_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft12_1'>错误</button>
    <div id='div_ft12_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft12_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft12_1'>错误</button>
    <div id='div_ft12_1' class="collapse in">
    <pre>
    
ft12_1: 2018-09-04 22:38:52,344 - root - INFO - ############################### START ###############################
2018-09-04 22:39:48,345 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\rjzztest.py", line 39, in test_rjzz
    self.assertIn("软件著作权登记-权大师",self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft12_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_rjzz_j: 软件著作权登记</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft12_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft12_2'>错误</button>
    <div id='div_ft12_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft12_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft12_2'>错误</button>
    <div id='div_ft12_2' class="collapse in">
    <pre>
    
ft12_2: 2018-09-04 22:39:48,374 - root - INFO - ############################### START ###############################
2018-09-04 22:40:43,718 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\rjzztest.py", line 99, in test_rjzz_j
    self.assertIn("软件著作权登记加急-权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>sbnumtest.SbNumTest: 相似商标个数测试集</td>
    <td class="text-center">2</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">1</td>
    <td class="text-center"><a href="javascript:showClassDetail('c13',2)" class="detail" id='c13'>详细</a></td>
</tr>

<tr id='ft13_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_number1: 智能注册_自助商标跳转测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft13_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft13_1'>错误</button>
    <div id='div_ft13_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft13_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft13_1'>错误</button>
    <div id='div_ft13_1' class="collapse in">
    <pre>
    
ft13_1: 2018-09-04 22:40:43,730 - root - INFO - ############################### START ###############################
智能商标注册-权大师
费用总计:300.00
商标名称：梯伙剑
2018-09-04 22:41:47,595 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\sbnumtest.py", line 51, in test_number1
    "#section-selfchoice &gt; div.group-left &gt; ul &gt; li:nth-child({}) &gt; span".format(suiji)).click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 437, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#section-selfchoice &gt; div.group-left &gt; ul &gt; li:nth-child(46) &gt; span"}
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='pt13_2' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_number2: 智能注册_推荐商标跳转测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt13_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt13_2'>通过</button>
    <div id='div_pt13_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt13_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt13_2'>通过</button>
    <div id='div_pt13_2' class="collapse in">
    <pre>
    
pt13_2: 2018-09-04 22:41:47,627 - root - INFO - ############################### START ###############################
智能商标注册-权大师
费用总计:300.00
商标名称：剖
选择所在领域：文教娱|文化.传媒.娱乐.教育_旅游行业
已为您检索到0条近似商标
0
权大师为您找到相关结果0个
检索相似商标数量一致,测试通过！
2018-09-04 22:42:28,051 - root - INFO - ###############################  End  ###############################


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>sbxxtest.SbXxTest: 商标信息测试集</td>
    <td class="text-center">5</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">5</td>
    <td class="text-center"><a href="javascript:showClassDetail('c14',5)" class="detail" id='c14'>详细</a></td>
</tr>

<tr id='ft14_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_sbbg: 商标变更测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft14_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft14_1'>错误</button>
    <div id='div_ft14_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft14_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft14_1'>错误</button>
    <div id='div_ft14_1' class="collapse in">
    <pre>
    
ft14_1: 2018-09-04 22:42:28,061 - root - INFO - ############################### START ###############################
商标变更-权大师
费用总计:1249.00
2018-09-04 22:42:56,032 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\sbxxtest.py", line 281, in test_sbbg
    self.driver.find_element_by_name("ownerContactPerson").send_keys("全大师")
AttributeError: 'NoneType' object has no attribute 'send_keys'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft14_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_sbkz: 商标宽展测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft14_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft14_2'>错误</button>
    <div id='div_ft14_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft14_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft14_2'>错误</button>
    <div id='div_ft14_2' class="collapse in">
    <pre>
    
ft14_2: 2018-09-04 22:42:56,068 - root - INFO - ############################### START ###############################
商标宽展-权大师
费用总计:2249.00
2018-09-04 22:43:25,056 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\sbxxtest.py", line 166, in test_sbkz
    self.driver.find_element_by_name("ownerContactPerson").send_keys("全大师")
AttributeError: 'NoneType' object has no attribute 'send_keys'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft14_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_sbxk: 商标许可备案测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft14_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft14_3'>错误</button>
    <div id='div_ft14_3' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft14_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft14_3'>错误</button>
    <div id='div_ft14_3' class="collapse in">
    <pre>
    
ft14_3: 2018-09-04 22:43:25,090 - root - INFO - ############################### START ###############################
商标许可备案-权大师
费用总计:749.00
2018-09-04 22:43:52,176 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\sbxxtest.py", line 224, in test_sbxk
    self.driver.find_element_by_name("ownerContactPerson").send_keys("全大师")
AttributeError: 'NoneType' object has no attribute 'send_keys'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft14_4' class='none'>
    <td class='errorCase'><div class='testcase'>test_sbxz: 商标续展让测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft14_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft14_4'>错误</button>
    <div id='div_ft14_4' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft14_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft14_4'>错误</button>
    <div id='div_ft14_4' class="collapse in">
    <pre>
    
ft14_4: 2018-09-04 22:43:52,196 - root - INFO - ############################### START ###############################
商标续展-权大师
费用总计:1999.00
2018-09-04 22:44:50,259 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\sbxxtest.py", line 108, in test_sbxz
    self.driver.find_element_by_name("ownerContactPerson").send_keys("全大师")
AttributeError: 'NoneType' object has no attribute 'send_keys'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft14_5' class='none'>
    <td class='errorCase'><div class='testcase'>test_sbzr: 商标转让测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft14_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft14_5'>错误</button>
    <div id='div_ft14_5' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft14_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft14_5'>错误</button>
    <div id='div_ft14_5' class="collapse in">
    <pre>
    
ft14_5: 2018-09-04 22:44:50,271 - root - INFO - ############################### START ###############################
商标转让-权大师
费用总计:1499.00
2018-09-04 22:45:18,381 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\sbxxtest.py", line 50, in test_sbzr
    self.driver.find_element_by_name("ownerContactPerson").send_keys("全大师")
AttributeError: 'NoneType' object has no attribute 'send_keys'


    </pre>
    </div>
    </td>
</tr>

<tr class='passClass warning'>
    <td>websitest.WebSiTest: 相似商标个数测试集</td>
    <td class="text-center">1</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c15',1)" class="detail" id='c15'>详细</a></td>
</tr>

<tr id='pt15_1' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_number1: 网站地图测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt15_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt15_1'>通过</button>
    <div id='div_pt15_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt15_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt15_1'>通过</button>
    <div id='div_pt15_1' class="collapse in">
    <pre>
    
pt15_1: 2018-09-04 22:45:18,417 - root - INFO - ############################### START ###############################
https://pre-www.quandashi.com/
https://pre-www.quandashi.com/home/index
https://pre-www.quandashi.com/daiinfo/index
javascript:void(0);
javascript:void(0);
https://pre-account.quandashi.com/passport/login?callback=https%3A%2F%2Fpre-www.quandashi.com%2F
https://pre-account.quandashi.com/passport/register
https://pre-www.quandashi.com/
https://pre-www.quandashi.com/sb
https://pre-www.quandashi.com/#
javascript:;
https://pre-so.quandashi.com/
https://pre-www.quandashi.com/sb/gnsbcx
javascript:;
https://pre-www.quandashi.com/sb/bmkszc/4
https://pre-www.quandashi.com/sb/dbwyzc/4
https://pre-www.quandashi.com/sb/znzzzc/4
https://pre-www.quandashi.com/sb/hwgsznzc/4
javascript:;
https://pre-www.quandashi.com/sb/sbbhfs
https://pre-www.quandashi.com/sb/sbyydb
https://pre-www.quandashi.com/sb/sbcsdb
javascript:;
https://pre-www.quandashi.com/sb/sbcssq
https://pre-www.quandashi.com/sb/sbyysq
https://pre-www.quandashi.com/sb/sbwxxgsq
javascript:;
https://pre-www.quandashi.com/sb/sbzr
https://pre-www.quandashi.com/sb/sbxz
https://pre-www.quandashi.com/sb/sbkz
https://pre-www.quandashi.com/sb/sbxkba
https://pre-www.quandashi.com/sb/sbbg
javascript:;
https://pre-www.quandashi.com/sb/mdl
https://pre-www.quandashi.com/sb/mgsbzc
https://pre-www.quandashi.com/sb/omsbzc
https://pre-www.quandashi.com/sb/rbsbzc
https://pre-www.quandashi.com/sb/ydsbzc
https://pre-www.quandashi.com/sb/xgsbzc
https://pre-www.quandashi.com/zl
javascript:;
https://pre-www.quandashi.com/third-order/trade-mark/335.html
javascript:;
https://pre-www.quandashi.com/third-order/trade-mark/667.html
https://pre-www.quandashi.com/third-order/trade-mark/668.html
javascript:;
https://pre-www.quandashi.com/third-order/trade-mark/671.html
https://pre-www.quandashi.com/third-order/trade-mark/673.html
javascript:;
https://pre-www.quandashi.com/third-order/trade-mark/669.html
https://pre-www.quandashi.com/third-order/trade-mark/670.html
javascript:;
https://pre-www.quandashi.com/third-order/trade-mark/14.html
https://pre-www.quandashi.com/third-order/trade-mark/15.html
https://pre-www.quandashi.com/third-order/trade-mark/40.html
javascript:;
https://pre-www.quandashi.com/third-order/trade-mark/42.html
https://pre-www.quandashi.com/third-order/trade-mark/446.html
https://pre-www.quandashi.com/bq
javascript:;
https://pre-www.quandashi.com/third-order/trade-mark/120.html
https://pre-www.quandashi.com/third-order/trade-mark/19.html
javascript:;
https://pre-www.quandashi.com/third-order/trade-mark/20.html
https://pre-www.quandashi.com/third-order/trade-mark/121.html
https://pre-www.quandashi.com/third-order/trade-mark/308.html
https://pre-www.quandashi.com/third-order/trade-mark/309.html
javascript:;
https://pre-www.quandashi.com/third-order/trade-mark/21.html
https://pre-www.quandashi.com/third-order/trade-mark/22.html
https://pre-www.quandashi.com/third-order/trade-mark/23.html
https://pre-www.quandashi.com/zhuanti/hhr.html
javascript:;
https://pre-www.quandashi.com/#
None
https://pre-www.quandashi.com/sb/bmkszc/4
javascript:;
https://pre-www.quandashi.com/zhuanti/hhr.html
javascript:void (0)
https://pre-account.quandashi.com/passport/login?callback=https%3A%2F%2Fpre-www.quandashi.com%2F
https://pre-account.quandashi.com/passport/register
https://pre-www.quandashi.com/sb
https://pre-www.quandashi.com/#
javascript:;
https://pre-so.quandashi.com/
https://pre-www.quandashi.com/sb/gnsbcx
javascript:;
https://pre-www.quandashi.com/sb/bmkszc/4
https://pre-www.quandashi.com/sb/dbwyzc/4
https://pre-www.quandashi.com/sb/znzzzc/4
https://pre-www.quandashi.com/sb/hwgsznzc/4
javascript:;
https://pre-www.quandashi.com/sb/sbbhfs
https://pre-www.quandashi.com/sb/sbyydb
https://pre-www.quandashi.com/sb/sbcsdb
javascript:;
https://pre-www.quandashi.com/sb/sbcssq
https://pre-www.quandashi.com/sb/sbyysq
https://pre-www.quandashi.com/sb/sbwxxgsq
javascript:;
https://pre-www.quandashi.com/sb/sbzr
https://pre-www.quandashi.com/sb/sbxz
https://pre-www.quandashi.com/sb/sbkz
https://pre-www.quandashi.com/sb/sbxkba
https://pre-www.quandashi.com/sb/sbbg
javascript:;
https://pre-www.quandashi.com/sb/mdl
https://pre-www.quandashi.com/sb/mgsbzc
https://pre-www.quandashi.com/sb/omsbzc
https://pre-www.quandashi.com/sb/rbsbzc
https://pre-www.quandashi.com/sb/ydsbzc
https://pre-www.quandashi.com/sb/xgsbzc
https://pre-www.quandashi.com/zl
javascript:;
https://pre-www.quandashi.com/third-order/trade-mark/335.html
javascript:;
https://pre-www.quandashi.com/third-order/trade-mark/667.html
https://pre-www.quandashi.com/third-order/trade-mark/668.html
javascript:;
https://pre-www.quandashi.com/third-order/trade-mark/671.html
https://pre-www.quandashi.com/third-order/trade-mark/673.html
javascript:;
https://pre-www.quandashi.com/third-order/trade-mark/669.html
https://pre-www.quandashi.com/third-order/trade-mark/670.html
javascript:;
https://pre-www.quandashi.com/third-order/trade-mark/14.html
https://pre-www.quandashi.com/third-order/trade-mark/15.html
https://pre-www.quandashi.com/third-order/trade-mark/40.html
javascript:;
https://pre-www.quandashi.com/third-order/trade-mark/42.html
https://pre-www.quandashi.com/third-order/trade-mark/446.html
https://pre-www.quandashi.com/bq
javascript:;
https://pre-www.quandashi.com/third-order/trade-mark/120.html
https://pre-www.quandashi.com/third-order/trade-mark/19.html
javascript:;
https://pre-www.quandashi.com/third-order/trade-mark/20.html
https://pre-www.quandashi.com/third-order/trade-mark/121.html
https://pre-www.quandashi.com/third-order/trade-mark/308.html
https://pre-www.quandashi.com/third-order/trade-mark/309.html
javascript:;
https://pre-www.quandashi.com/third-order/trade-mark/21.html
https://pre-www.quandashi.com/third-order/trade-mark/22.html
https://pre-www.quandashi.com/third-order/trade-mark/23.html
https://pre-www.quandashi.com/zhuanti/hhr.html
javascript:;
https://pre-www.quandashi.com/#
None
https://pre-www.quandashi.com/sb/bmkszc/4
javascript:;
https://pre-www.quandashi.com/zhuanti/hhr.html
https://pre-so.quandashi.com/index/search?key=%E4%BC%97%E5%86%89
https://pre-so.quandashi.com/index/search?key=WALDADA
https://pre-so.quandashi.com/index/search?key=%E5%9D%9A%E5%86%B0JNBN
https://pre-so.quandashi.com/index/search?key=S
https://pre-so.quandashi.com/index/search?key=CRJH
https://pre-so.quandashi.com/index/search?key=%E9%87%8D%E6%B7%B7%E5%85%B1%E4%BA%AB%E6%AD%A3%E8%83%BD%E9%87%8F
https://pre-www.quandashi.com/zhuanti/hhr
https://pre-www.quandashi.com/#
https://so.quandashi.com/
https://pre-www.quandashi.com/sb
https://pre-www.quandashi.com/sb
https://pre-www.quandashi.com/sb
https://pre-www.quandashi.com/sb
https://pre-www.quandashi.com/zl
https://pre-www.quandashi.com/zl
https://pre-www.quandashi.com/zl
https://pre-www.quandashi.com/zl
https://pre-www.quandashi.com/zl
https://pre-www.quandashi.com/bq
https://pre-www.quandashi.com/bq
https://pre-www.quandashi.com/bq
https://pre-www.quandashi.com/bq
javascript:;
https://pre-www.quandashi.com/brand-order/basemsg/PC1003/0.html
javascript:;
None
javascript:;
https://pre-so.quandashi.com/index/nisi.html
https://pre-www.quandashi.com/news/newdetail/12812.html
https://pre-www.quandashi.com/news/newdetail/12812.html
https://pre-www.quandashi.com/news/newdetail/12811.html
https://pre-www.quandashi.com/news/newdetail/12798.html
https://pre-www.quandashi.com/news/industry?type=28
https://pre-www.quandashi.com/news/newdetail/12820.html
https://pre-www.quandashi.com/news/newdetail/12820.html
https://pre-www.quandashi.com/news/newdetail/12819.html
https://pre-www.quandashi.com/news/newdetail/12818.html
https://pre-www.quandashi.com/news/index.html
https://pre-www.quandashi.com/question/detail/8.html
https://pre-www.quandashi.com/question/detail/8.html
https://pre-www.quandashi.com/question/detail/2.html
https://pre-www.quandashi.com/question/detail/2.html
https://pre-www.quandashi.com/question/detail/22.html
https://pre-www.quandashi.com/question/detail/22.html
https://pre-www.quandashi.com/question/index.html
http://www.sipo.gov.cn/
http://www.sipop.cn/gate/index.html
http://www.ciptc.org.cn/
http://www.zgc.gov.cn/
http://www.elht.com/Business/53.aspx
http://www.sipac.gov.cn/
http://www.qixin.com/
https://www.tencent.com/
https://www.baidu.com/
http://www.haier.com/cn/
http://www.ofo.so/#/
http://www.pku.edu.cn/
http://www.kingdee.com/
https://pre-www.quandashi.com/index/about/1.html
https://pre-www.quandashi.com/index/about/2.html
https://pre-www.quandashi.com/index/about/3.html
https://pre-www.quandashi.com/index/about/5.html
https://pre-www.quandashi.com/index/about/8.html
https://pre-www.quandashi.com/index/about/11.html
https://pre-www.quandashi.com/site-map/index
https://v.pinpaibao.com.cn/authenticate/cert/?site=pre-www.quandashi.com&amp;at=business
https://pre-www.quandashi.com/#
https://pre-www.quandashi.com/#
https://pre-www.quandashi.com/#
https://pre-www.quandashi.com/#
http://www.iprdaily.com/
https://www.quandashi.com/
https://www.quandashi.com/ztlist/shangbiao.html
https://www.quandashi.com/ztlist/zhuanli.html
https://www.quandashi.com/ztlist/banquan.html
https://www.quandashi.com/ztlist/qita.html
https://www.quandashi.com/sitemap.xml
https://www.quandashi.com/sitemap.html
javascript:void(0)
javascript:void(0)
javascript:void(0)
javascript:void(0)
https://pre-www.quandashi.com/#
https://pre-www.quandashi.com/zhuanti/hhr
https://pre-www.quandashi.com/#
https://pre-so.quandashi.com/
https://pre-www.quandashi.com/brand-order/basemsg/PC10003/0.html
https://so.quandashi.com/index/nisi
https://pre-www.quandashi.com/brand-monitor/index
https://pre-www.quandashi.com/brandmanage/index
javascript:void(0)
javascript:void(0)
https://pre-so.quandashi.com/shangbiao/
https://pre-so.quandashi.com/
None
2018-09-04 22:45:46,326 - root - INFO - ###############################  End  ###############################


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>yytrtest.YyTrTest: 异议他人商标测试集</td>
    <td class="text-center">3</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">3</td>
    <td class="text-center"><a href="javascript:showClassDetail('c16',3)" class="detail" id='c16'>详细</a></td>
</tr>

<tr id='ft16_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_sbcs: 商标撤三测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft16_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft16_1'>错误</button>
    <div id='div_ft16_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft16_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft16_1'>错误</button>
    <div id='div_ft16_1' class="collapse in">
    <pre>
    
ft16_1: 2018-09-04 22:45:46,343 - root - INFO - ############################### START ###############################
商标撤三申请-权大师
费用总计:1499.00
2018-09-04 22:46:13,453 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\yytrtest.py", line 47, in test_sbcs
    self.driver.find_element_by_name("ownerContactPerson").send_keys("全大师")
AttributeError: 'NoneType' object has no attribute 'send_keys'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft16_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_sbwx: 商标无效宣告申请测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft16_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft16_2'>错误</button>
    <div id='div_ft16_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft16_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft16_2'>错误</button>
    <div id='div_ft16_2' class="collapse in">
    <pre>
    
ft16_2: 2018-09-04 22:46:13,517 - root - INFO - ############################### START ###############################
商标无效宣告申请_流程_商标无效宣告费用_权大师
费用总计:3750.00
2018-09-04 22:46:41,637 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\yytrtest.py", line 163, in test_sbwx
    self.driver.find_element_by_name("ownerContactPerson").send_keys("全大师")
AttributeError: 'NoneType' object has no attribute 'send_keys'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft16_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_sbyy: 商标异议申请测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft16_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft16_3'>错误</button>
    <div id='div_ft16_3' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft16_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft16_3'>错误</button>
    <div id='div_ft16_3' class="collapse in">
    <pre>
    
ft16_3: 2018-09-04 22:46:41,652 - root - INFO - ############################### START ###############################
商标异议申请_商标异议申请流程_商标异议收费标准_权大师
费用总计:3500.00
2018-09-04 22:47:10,478 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\yytrtest.py", line 105, in test_sbyy
    self.driver.find_element_by_name("ownerContactPerson").send_keys("全大师")
AttributeError: 'NoneType' object has no attribute 'send_keys'


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>zahjtest.ZaHjTest: 遇到障碍如何化解测试集</td>
    <td class="text-center">3</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">3</td>
    <td class="text-center"><a href="javascript:showClassDetail('c17',3)" class="detail" id='c17'>详细</a></td>
</tr>

<tr id='ft17_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_sbbh: 商标驳回测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft17_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft17_1'>错误</button>
    <div id='div_ft17_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft17_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft17_1'>错误</button>
    <div id='div_ft17_1' class="collapse in">
    <pre>
    
ft17_1: 2018-09-04 22:47:10,504 - root - INFO - ############################### START ###############################
商标驳回复审-权大师
费用总计:2749.00
2018-09-04 22:47:41,354 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zahjtest.py", line 47, in test_sbbh
    self.driver.find_element_by_name("ownerContactPerson").send_keys("全大师")
AttributeError: 'NoneType' object has no attribute 'send_keys'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft17_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_sbcsdb: 商标撤三答辩测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft17_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft17_2'>错误</button>
    <div id='div_ft17_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft17_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft17_2'>错误</button>
    <div id='div_ft17_2' class="collapse in">
    <pre>
    
ft17_2: 2018-09-04 22:47:41,373 - root - INFO - ############################### START ###############################
商标撤三答辩-权大师
费用总计:2999.00
2018-09-04 22:48:16,117 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zahjtest.py", line 161, in test_sbcsdb
    self.driver.find_element_by_name("ownerContactPerson").send_keys("全大师")
AttributeError: 'NoneType' object has no attribute 'send_keys'


    </pre>
    </div>
    </td>
</tr>

<tr id='ft17_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_sbdb: 商标异议答辩测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft17_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft17_3'>错误</button>
    <div id='div_ft17_3' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft17_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft17_3'>错误</button>
    <div id='div_ft17_3' class="collapse in">
    <pre>
    
ft17_3: 2018-09-04 22:48:16,133 - root - INFO - ############################### START ###############################
商标异议答辩-权大师
费用总计:2999.00
2018-09-04 22:48:44,940 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zahjtest.py", line 104, in test_sbdb
    self.driver.find_element_by_name("ownerContactPerson").send_keys("全大师")
AttributeError: 'NoneType' object has no attribute 'send_keys'


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>zlywtest.ZlYwTest: 专利业务测试集</td>
    <td class="text-center">24</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">24</td>
    <td class="text-center"><a href="javascript:showClassDetail('c18',24)" class="detail" id='c18'>详细</a></td>
</tr>

<tr id='ft18_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_cpwgbz_1: 产品外观标准_单个申请人减缓测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft18_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft18_1'>错误</button>
    <div id='div_ft18_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft18_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft18_1'>错误</button>
    <div id='div_ft18_1' class="collapse in">
    <pre>
    
ft18_1: 2018-09-04 22:48:44,976 - root - INFO - ############################### START ###############################
2018-09-04 22:49:41,198 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zlywtest.py", line 95, in test_cpwgbz_1
    self.assertIn("外观设计专利标准申请|专利申请|专利查询|权大师",self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft18_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_cpwgbz_2: 产品外观标准_多个申请人减缓测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft18_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft18_2'>错误</button>
    <div id='div_ft18_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft18_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft18_2'>错误</button>
    <div id='div_ft18_2' class="collapse in">
    <pre>
    
ft18_2: 2018-09-04 22:49:41,247 - root - INFO - ############################### START ###############################
2018-09-04 22:50:13,309 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zlywtest.py", line 161, in test_cpwgbz_2
    self.assertIn("外观设计专利标准申请|专利申请|专利查询|权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft18_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_cpwgbz_3: 产品外观标准_不减缓测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft18_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft18_3'>错误</button>
    <div id='div_ft18_3' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft18_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft18_3'>错误</button>
    <div id='div_ft18_3' class="collapse in">
    <pre>
    
ft18_3: 2018-09-04 22:50:13,343 - root - INFO - ############################### START ###############################
2018-09-04 22:51:09,089 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zlywtest.py", line 225, in test_cpwgbz_3
    self.assertIn("外观设计专利标准申请|专利申请|专利查询|权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft18_4' class='none'>
    <td class='errorCase'><div class='testcase'>test_cpwgdb_1: 产品外观担保_单个申请人减缓测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft18_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft18_4'>错误</button>
    <div id='div_ft18_4' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft18_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft18_4'>错误</button>
    <div id='div_ft18_4' class="collapse in">
    <pre>
    
ft18_4: 2018-09-04 22:51:09,098 - root - INFO - ############################### START ###############################
2018-09-04 22:52:03,994 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zlywtest.py", line 289, in test_cpwgdb_1
    self.assertIn("外观设计专利标准申请|专利申请|专利查询|权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft18_5' class='none'>
    <td class='errorCase'><div class='testcase'>test_cpwgdb_2: 产品外观担保_多个申请人减缓测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft18_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft18_5'>错误</button>
    <div id='div_ft18_5' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft18_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft18_5'>错误</button>
    <div id='div_ft18_5' class="collapse in">
    <pre>
    
ft18_5: 2018-09-04 22:52:04,014 - root - INFO - ############################### START ###############################
2018-09-04 22:52:32,936 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zlywtest.py", line 355, in test_cpwgdb_2
    self.assertIn("外观设计专利标准申请|专利申请|专利查询|权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft18_6' class='none'>
    <td class='errorCase'><div class='testcase'>test_cpwgdb_3: 产品外观担保_不减缓测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft18_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft18_6'>错误</button>
    <div id='div_ft18_6' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft18_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft18_6'>错误</button>
    <div id='div_ft18_6' class="collapse in">
    <pre>
    
ft18_6: 2018-09-04 22:52:32,965 - root - INFO - ############################### START ###############################
2018-09-04 22:53:28,161 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zlywtest.py", line 421, in test_cpwgdb_3
    self.assertIn("外观设计专利标准申请|专利申请|专利查询|权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft18_7' class='none'>
    <td class='errorCase'><div class='testcase'>test_guibz_1: GUI标准_单个申请人减缓</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft18_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft18_7'>错误</button>
    <div id='div_ft18_7' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft18_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft18_7'>错误</button>
    <div id='div_ft18_7' class="collapse in">
    <pre>
    
ft18_7: 2018-09-04 22:53:28,192 - root - INFO - ############################### START ###############################
2018-09-04 22:54:23,137 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zlywtest.py", line 485, in test_guibz_1
    self.assertIn("GUI及系列产品标准申请|专利申请|专利查询|权大师",self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft18_8' class='none'>
    <td class='errorCase'><div class='testcase'>test_guibz_2: GUI标准_多个申请人减缓</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft18_8' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft18_8'>错误</button>
    <div id='div_ft18_8' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft18_8' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft18_8'>错误</button>
    <div id='div_ft18_8' class="collapse in">
    <pre>
    
ft18_8: 2018-09-04 22:54:23,169 - root - INFO - ############################### START ###############################
2018-09-04 22:55:18,729 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zlywtest.py", line 548, in test_guibz_2
    self.assertIn("GUI及系列产品标准申请|专利申请|专利查询|权大师",self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft18_9' class='none'>
    <td class='errorCase'><div class='testcase'>test_guibz_3: GUI标准_不减缓</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft18_9' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft18_9'>错误</button>
    <div id='div_ft18_9' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft18_9' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft18_9'>错误</button>
    <div id='div_ft18_9' class="collapse in">
    <pre>
    
ft18_9: 2018-09-04 22:55:18,761 - root - INFO - ############################### START ###############################
2018-09-04 22:56:13,832 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zlywtest.py", line 611, in test_guibz_3
    self.assertIn("GUI及系列产品标准申请|专利申请|专利查询|权大师",self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft18_10' class='none'>
    <td class='errorCase'><div class='testcase'>test_guidb_1: GUI担保_单个申请人减缓</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft18_10' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft18_10'>错误</button>
    <div id='div_ft18_10' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft18_10' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft18_10'>错误</button>
    <div id='div_ft18_10' class="collapse in">
    <pre>
    
ft18_10: 2018-09-04 22:56:13,865 - root - INFO - ############################### START ###############################
2018-09-04 22:57:10,349 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zlywtest.py", line 674, in test_guidb_1
    self.assertIn("GUI及系列产品标准申请|专利申请|专利查询|权大师",self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft18_11' class='none'>
    <td class='errorCase'><div class='testcase'>test_guidb_2: GUI担保_多个申请人减缓</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft18_11' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft18_11'>错误</button>
    <div id='div_ft18_11' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft18_11' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft18_11'>错误</button>
    <div id='div_ft18_11' class="collapse in">
    <pre>
    
ft18_11: 2018-09-04 22:57:10,377 - root - INFO - ############################### START ###############################
2018-09-04 22:57:39,103 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zlywtest.py", line 738, in test_guidb_2
    self.assertIn("GUI及系列产品标准申请|专利申请|专利查询|权大师",self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft18_12' class='none'>
    <td class='errorCase'><div class='testcase'>test_guidb_3: GUI担保_不减缓</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft18_12' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft18_12'>错误</button>
    <div id='div_ft18_12' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft18_12' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft18_12'>错误</button>
    <div id='div_ft18_12' class="collapse in">
    <pre>
    
ft18_12: 2018-09-04 22:57:39,125 - root - INFO - ############################### START ###############################
2018-09-04 22:58:09,558 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zlywtest.py", line 800, in test_guidb_3
    self.assertIn("GUI及系列产品标准申请|专利申请|专利查询|权大师",self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft18_13' class='none'>
    <td class='errorCase'><div class='testcase'>test_nfjn: 年费缴纳测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft18_13' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft18_13'>错误</button>
    <div id='div_ft18_13' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft18_13' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft18_13'>错误</button>
    <div id='div_ft18_13' class="collapse in">
    <pre>
    
ft18_13: 2018-09-04 22:58:09,590 - root - INFO - ############################### START ###############################
2018-09-04 22:59:04,144 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zlywtest.py", line 1537, in test_nfjn
    self.assertIn("发明专利年费缴纳-权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft18_14' class='none'>
    <td class='errorCase'><div class='testcase'>test_syzlbz_1: 标准型-单个申请人减缓</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft18_14' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft18_14'>错误</button>
    <div id='div_ft18_14' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft18_14' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft18_14'>错误</button>
    <div id='div_ft18_14' class="collapse in">
    <pre>
    
ft18_14: 2018-09-04 22:59:04,171 - root - INFO - ############################### START ###############################
2018-09-04 22:59:57,722 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zlywtest.py", line 865, in test_syzlbz_1
    self.assertIn("实用新型专利标准申请|专利申请|专利查询|权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft18_15' class='none'>
    <td class='errorCase'><div class='testcase'>test_syzlbz_2: 标准型-多个申请人减缓</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft18_15' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft18_15'>错误</button>
    <div id='div_ft18_15' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft18_15' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft18_15'>错误</button>
    <div id='div_ft18_15' class="collapse in">
    <pre>
    
ft18_15: 2018-09-04 22:59:57,748 - root - INFO - ############################### START ###############################
2018-09-04 23:00:52,005 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zlywtest.py", line 929, in test_syzlbz_2
    self.assertIn("实用新型专利标准申请|专利申请|专利查询|权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft18_16' class='none'>
    <td class='errorCase'><div class='testcase'>test_syzlbz_3: 标准型-不减缓</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft18_16' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft18_16'>错误</button>
    <div id='div_ft18_16' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft18_16' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft18_16'>错误</button>
    <div id='div_ft18_16' class="collapse in">
    <pre>
    
ft18_16: 2018-09-04 23:00:52,037 - root - INFO - ############################### START ###############################
2018-09-04 23:01:20,909 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zlywtest.py", line 993, in test_syzlbz_3
    self.assertIn("实用新型专利标准申请|专利申请|专利查询|权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft18_17' class='none'>
    <td class='errorCase'><div class='testcase'>test_syzldb_1: 担保型-单个申请人减缓</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft18_17' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft18_17'>错误</button>
    <div id='div_ft18_17' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft18_17' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft18_17'>错误</button>
    <div id='div_ft18_17' class="collapse in">
    <pre>
    
ft18_17: 2018-09-04 23:01:20,918 - root - INFO - ############################### START ###############################
2018-09-04 23:02:16,004 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zlywtest.py", line 1057, in test_syzldb_1
    self.assertIn("实用新型专利担保申请|专利申请|专利查询|权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft18_18' class='none'>
    <td class='errorCase'><div class='testcase'>test_syzldb_2: 担保型-多个申请人减缓</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft18_18' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft18_18'>错误</button>
    <div id='div_ft18_18' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft18_18' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft18_18'>错误</button>
    <div id='div_ft18_18' class="collapse in">
    <pre>
    
ft18_18: 2018-09-04 23:02:16,036 - root - INFO - ############################### START ###############################
2018-09-04 23:02:43,543 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zlywtest.py", line 1121, in test_syzldb_2
    self.assertIn("实用新型专利担保申请|专利申请|专利查询|权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft18_19' class='none'>
    <td class='errorCase'><div class='testcase'>test_syzldb_3: 担保型-不减缓</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft18_19' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft18_19'>错误</button>
    <div id='div_ft18_19' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft18_19' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft18_19'>错误</button>
    <div id='div_ft18_19' class="collapse in">
    <pre>
    
ft18_19: 2018-09-04 23:02:43,575 - root - INFO - ############################### START ###############################
2018-09-04 23:03:37,146 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zlywtest.py", line 1184, in test_syzldb_3
    self.assertIn("实用新型专利担保申请|专利申请|专利查询|权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft18_20' class='none'>
    <td class='errorCase'><div class='testcase'>test_zlbg: 专利著录项变更测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft18_20' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft18_20'>错误</button>
    <div id='div_ft18_20' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft18_20' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft18_20'>错误</button>
    <div id='div_ft18_20' class="collapse in">
    <pre>
    
ft18_20: 2018-09-04 23:03:37,171 - root - INFO - ############################### START ###############################
2018-09-04 23:04:31,100 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zlywtest.py", line 1601, in test_zlbg
    self.assertIn("专利著录项变更-权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft18_21' class='none'>
    <td class='errorCase'><div class='testcase'>test_zlbh: 专利驳回复审测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft18_21' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft18_21'>错误</button>
    <div id='div_ft18_21' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft18_21' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft18_21'>错误</button>
    <div id='div_ft18_21' class="collapse in">
    <pre>
    
ft18_21: 2018-09-04 23:04:31,120 - root - INFO - ############################### START ###############################
2018-09-04 23:04:59,682 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zlywtest.py", line 1364, in test_zlbh
    self.assertIn("发明专利驳回复审_权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft18_22' class='none'>
    <td class='errorCase'><div class='testcase'>test_zldb: 发明专利无效答辩测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft18_22' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft18_22'>错误</button>
    <div id='div_ft18_22' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft18_22' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft18_22'>错误</button>
    <div id='div_ft18_22' class="collapse in">
    <pre>
    
ft18_22: 2018-09-04 23:04:59,714 - root - INFO - ############################### START ###############################
2018-09-04 23:05:54,481 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zlywtest.py", line 1479, in test_zldb
    self.assertIn("发明专利无效答辩_权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft18_23' class='none'>
    <td class='errorCase'><div class='testcase'>test_zljs: 专利查新检索（报告）测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft18_23' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft18_23'>错误</button>
    <div id='div_ft18_23' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft18_23' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft18_23'>错误</button>
    <div id='div_ft18_23' class="collapse in">
    <pre>
    
ft18_23: 2018-09-04 23:05:54,494 - root - INFO - ############################### START ###############################
2018-09-04 23:06:50,061 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zlywtest.py", line 35, in test_zljs
    self.assertIn("专利查新检索（报告）_权大师",self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr id='ft18_24' class='none'>
    <td class='errorCase'><div class='testcase'>test_zlxg: 专利无效宣告测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft18_24' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft18_24'>错误</button>
    <div id='div_ft18_24' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft18_24' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft18_24'>错误</button>
    <div id='div_ft18_24' class="collapse in">
    <pre>
    
ft18_24: 2018-09-04 23:06:50,091 - root - INFO - ############################### START ###############################
2018-09-04 23:07:44,233 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\zlywtest.py", line 1422, in test_zlxg
    self.assertIn("专利无效宣告_权大师", self.driver.title)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 1079, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
TypeError: 'str' object is not callable


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>znzztest.ZnZzTest: 智能注册测试集</td>
    <td class="text-center">2</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">2</td>
    <td class="text-center"><a href="javascript:showClassDetail('c19',2)" class="detail" id='c19'>详细</a></td>
</tr>

<tr id='ft19_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_znzz_1: 智能注册_企业测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft19_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft19_1'>错误</button>
    <div id='div_ft19_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft19_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft19_1'>错误</button>
    <div id='div_ft19_1' class="collapse in">
    <pre>
    
ft19_1: 2018-09-04 23:07:44,253 - root - INFO - ############################### START ###############################
智能商标注册-权大师
费用总计:300.00
商标名称：fAlaska
选择了第16类商标分类!
2018-09-04 23:09:15,966 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\znzztest.py", line 105, in test_znzz_1
    "body &gt; div.smartRegister-page &gt; div.agentInfo-wrap.applicant-wrap &gt; div.section-base &gt; div.applicant-form &gt; table.table-1.table-applicant.table-type1.active &gt; tbody.tbody-qiye &gt; tr:nth-child(1) &gt; td.td-content.contact-select-container &gt; dl &gt; dt &gt; input").clear()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 437, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"body &gt; div.smartRegister-page &gt; div.agentInfo-wrap.applicant-wrap &gt; div.section-base &gt; div.applicant-form &gt; table.table-1.table-applicant.table-type1.active &gt; tbody.tbody-qiye &gt; tr:nth-child(1) &gt; td.td-content.contact-select-container &gt; dl &gt; dt &gt; input"}
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft19_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_znzz_2: 智能注册_个体测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft19_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft19_2'>错误</button>
    <div id='div_ft19_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft19_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft19_2'>错误</button>
    <div id='div_ft19_2' class="collapse in">
    <pre>
    
ft19_2: 2018-09-04 23:09:16,057 - root - INFO - ############################### START ###############################
智能商标注册-权大师
费用总计:300.00
商标名称：fAnastasia
选择了第2类商标分类!
2018-09-04 23:10:53,586 - root - INFO - ###############################  End  ###############################
Traceback (most recent call last):
  File "G:\QDS_company\case\znzztest.py", line 254, in test_znzz_2
    self.driver.find_element_by_css_selector("body &gt; div.smartRegister-page &gt; div.agentInfo-wrap.applicant-wrap &gt; div.section-base &gt; table &gt; thead &gt; tr &gt; td.td-content &gt; a:nth-child(2)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 437, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"body &gt; div.smartRegister-page &gt; div.agentInfo-wrap.applicant-wrap &gt; div.section-base &gt; table &gt; thead &gt; tr &gt; td.td-content &gt; a:nth-child(2)"}
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='total_row' class="text-center active">
    <td>总计</td>
    <td>86</td>
    <td>4</td>
    <td>0</td>
    <td>82</td>
    <td>通过率：4.65%</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>
    <div style=" position:fixed;right:50px; bottom:30px; width:20px; height:20px;cursor:pointer">
    <a href="#"><span class="glyphicon glyphicon-eject" style = "font-size:30px;" aria-hidden="true">
    </span></a></div>
    

</body>
</html>
