<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>权大师测试报告</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    
<style type="text/css" media="screen">
body        { font-family: Microsoft YaHei,Tahoma,arial,helvetica,sans-serif;padding: 20px; font-size: 80%; }
table       { font-size: 100%; }

/* -- heading ---------------------------------------------------------------------- */
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}

.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}

/* -- report ------------------------------------------------------------------------ */
#total_row  { font-weight: bold; }
.passCase   { color: #5cb85c; }
.failCase   { color: #d9534f; font-weight: bold; }
.errorCase  { color: #f0ad4e; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }
</style>

</head>
<body >
<script language="javascript" type="text/javascript">
output_list = Array();

/*level 调整增加只显示通过用例的分类 --Findyou
0:Summary //all hiddenRow
1:Failed  //pt hiddenRow, ft none
2:Pass    //pt none, ft hiddenRow
3:All     //pt none, ft none
*/
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level == 2 || level == 0 ) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level < 2) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
    }

    //加入【详细】切换文字变化 --Findyou
    detail_class=document.getElementsByClassName('detail');
	//console.log(detail_class.length)
	if (level == 3) {
		for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="收起"
		}
	}
	else{
			for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="详细"
		}
	}
}

function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        //ID修改 点 为 下划线 -Findyou
        tid0 = 't' + cid.substr(1) + '_' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        //修改点击无法收起的BUG，加入【详细】切换文字变化 --Findyou
        if (toHide) {
            document.getElementById(tid).className = 'hiddenRow';
            document.getElementById(cid).innerText = "详细"
        }
        else {
            document.getElementById(tid).className = '';
            document.getElementById(cid).innerText = "收起"
        }
    }
}

function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}
</script>
<div class='heading'>
<h1 style="font-family: Microsoft YaHei">权大师测试报告</h1>
<p class='attribute'><strong>测试人员 : </strong> lijiawei</p>
<p class='attribute'><strong>开始时间 : </strong> 2018-08-07 12:00:00</p>
<p class='attribute'><strong>合计耗时 : </strong> 0:25:50.077195</p>
<p class='attribute'><strong>测试结果 : </strong> 共 55，通过 6，失败 1，错误 48，通过率= 10.91%</p>

<p class='description'>Environment:  OS:win10  Browser:chrome</p>
</div>



<p id='show_detail_line'>
<a class="btn btn-primary" href='javascript:showCase(0)'>概要{ 10.91% }</a>
<a class="btn btn-danger" href='javascript:showCase(1)'>失败{ 1 }</a>
<a class="btn btn-success" href='javascript:showCase(2)'>通过{ 6 }</a>
<a class="btn btn-info" href='javascript:showCase(3)'>所有{ 55 }</a>
</p>
<table id='result_table' class="table table-condensed table-bordered table-hover">
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row' class="text-center success" style="font-weight: bold;font-size: 14px;">
    <td>用例集/测试用例</td>
    <td>总计</td>
    <td>通过</td>
    <td>失败</td>
    <td>错误</td>
    <td>详细</td>
</tr>

<tr class='passClass warning'>
    <td>bmkstest.bmkstest: 保姆注册测试集</td>
    <td class="text-center">1</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c1',1)" class="detail" id='c1'>详细</a></td>
</tr>

<tr id='pt1_1' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_bmks: 保姆快速注册</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt1_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt1_1'>通过</button>
    <div id='div_pt1_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt1_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt1_1'>通过</button>
    <div id='div_pt1_1' class="collapse in">
    <pre>
    
pt1_1: 商标注册-权大师
费用总计:600.00
总价:600.00
价格一致
订单提交成功，应付金额:600.00
测试通过


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>bqywtest.bqywtest: 版权业务测试集</td>
    <td class="text-center">7</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">7</td>
    <td class="text-center"><a href="javascript:showClassDetail('c2',7)" class="detail" id='c2'>详细</a></td>
</tr>

<tr id='ft2_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_msdj: 美术作品版权登记加急测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_1'>错误</button>
    <div id='div_ft2_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_1'>错误</button>
    <div id='div_ft2_1' class="collapse in">
    <pre>
    
ft2_1: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\bqywtest.py", line 87, in test_msdj
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(3) &gt; div &gt; dl:nth-child(2) &gt; dd &gt; a:nth-child(2)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_mszp: 美术作品版权登记测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_2'>错误</button>
    <div id='div_ft2_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_2'>错误</button>
    <div id='div_ft2_2' class="collapse in">
    <pre>
    
ft2_2: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\bqywtest.py", line 30, in test_mszp
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(3) &gt; div &gt; dl:nth-child(2) &gt; dd &gt; a:nth-child(1)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_rjbg: 软件著作权变更测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_3'>错误</button>
    <div id='div_ft2_3' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_3'>错误</button>
    <div id='div_ft2_3' class="collapse in">
    <pre>
    
ft2_3: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\bqywtest.py", line 255, in test_rjbg
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(3) &gt; div &gt; dl:nth-child(3) &gt; dd &gt; a:nth-child(1)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_4' class='none'>
    <td class='errorCase'><div class='testcase'>test_rjbz: 软件著作权补证测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_4'>错误</button>
    <div id='div_ft2_4' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_4'>错误</button>
    <div id='div_ft2_4' class="collapse in">
    <pre>
    
ft2_4: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\bqywtest.py", line 313, in test_rjbz
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(3) &gt; div &gt; dl:nth-child(3) &gt; dd &gt; a:nth-child(2)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_5' class='none'>
    <td class='errorCase'><div class='testcase'>test_rjzr: 软件著作权转让测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_5'>错误</button>
    <div id='div_ft2_5' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_5'>错误</button>
    <div id='div_ft2_5' class="collapse in">
    <pre>
    
ft2_5: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\bqywtest.py", line 370, in test_rjzr
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(3) &gt; div &gt; dl:nth-child(3) &gt; dd &gt; a:nth-child(3)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_6' class='none'>
    <td class='errorCase'><div class='testcase'>test_wzdj: 文字作品版权登记加急测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_6'>错误</button>
    <div id='div_ft2_6' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_6'>错误</button>
    <div id='div_ft2_6' class="collapse in">
    <pre>
    
ft2_6: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\bqywtest.py", line 199, in test_wzdj
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(3) &gt; div &gt; dl:nth-child(2) &gt; dd &gt; a:nth-child(4)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_7' class='none'>
    <td class='errorCase'><div class='testcase'>test_wzzp: 文字作品版权登记测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_7'>错误</button>
    <div id='div_ft2_7' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_7'>错误</button>
    <div id='div_ft2_7' class="collapse in">
    <pre>
    
ft2_7: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\bqywtest.py", line 143, in test_wzzp
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(3) &gt; div &gt; dl:nth-child(2) &gt; dd &gt; a:nth-child(3)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>cxzctest.cxzctest: 查询注册测试集</td>
    <td class="text-center">2</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">2</td>
    <td class="text-center"><a href="javascript:showClassDetail('c3',2)" class="detail" id='c3'>详细</a></td>
</tr>

<tr id='ft3_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_gnsb: 国内商标查询测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_1'>错误</button>
    <div id='div_ft3_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_1'>错误</button>
    <div id='div_ft3_1' class="collapse in">
    <pre>
    
ft3_1: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\cxzctest.py", line 62, in test_gnsb
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(1) &gt; div &gt; dl:nth-child(2) &gt; dd &gt; a:nth-child(2)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_mfsb: 免费商标查询测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_2'>错误</button>
    <div id='div_ft3_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_2'>错误</button>
    <div id='div_ft3_2' class="collapse in">
    <pre>
    
ft3_2: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\cxzctest.py", line 32, in test_mfsb
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(1) &gt; div &gt; dl:nth-child(2) &gt; dd &gt; a:nth-child(1)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr class='passClass warning'>
    <td>dbwytest.dbwytest: 担保无忧测试集</td>
    <td class="text-center">1</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c4',1)" class="detail" id='c4'>详细</a></td>
</tr>

<tr id='pt4_1' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_dbwy: 担保无忧测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt4_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt4_1'>通过</button>
    <div id='div_pt4_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt4_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt4_1'>通过</button>
    <div id='div_pt4_1' class="collapse in">
    <pre>
    
pt4_1: 商标注册-权大师
费用总计:1280.00
总价:1280.00
价格一致
订单提交成功，应付金额:1280.00
测试通过


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>fmzltest.fmzltest: 发明专利测试集</td>
    <td class="text-center">3</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">3</td>
    <td class="text-center"><a href="javascript:showClassDetail('c5',3)" class="detail" id='c5'>详细</a></td>
</tr>

<tr id='ft5_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_fmzl_1: 基础型-单个申请人减缓</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_1'>错误</button>
    <div id='div_ft5_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_1'>错误</button>
    <div id='div_ft5_1' class="collapse in">
    <pre>
    
ft5_1: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\fmzltest.py", line 33, in test_fmzl_1
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(2) &gt; div &gt; dl:nth-child(2) &gt; dd &gt; a:nth-child(1)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_fmzl_2: 防御型-多个申请人减缓</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_2'>错误</button>
    <div id='div_ft5_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_2'>错误</button>
    <div id='div_ft5_2' class="collapse in">
    <pre>
    
ft5_2: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\fmzltest.py", line 95, in test_fmzl_2
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(2) &gt; div &gt; dl:nth-child(2) &gt; dd &gt; a:nth-child(2)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft5_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_fmzl_3: 壁垒型-不减缓</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft5_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft5_3'>错误</button>
    <div id='div_ft5_3' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft5_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft5_3'>错误</button>
    <div id='div_ft5_3' class="collapse in">
    <pre>
    
ft5_3: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\fmzltest.py", line 157, in test_fmzl_3
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(2) &gt; div &gt; dl:nth-child(2) &gt; dd &gt; a:nth-child(3)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>hhrtest.hhrtest: 合伙人个人中心测试集</td>
    <td class="text-center">3</td>
    <td class="text-center">2</td>
    <td class="text-center">0</td>
    <td class="text-center">1</td>
    <td class="text-center"><a href="javascript:showClassDetail('c6',3)" class="detail" id='c6'>详细</a></td>
</tr>

<tr id='pt6_1' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_hhrqdxd: 渠道下单单个商标注册</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt6_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt6_1'>通过</button>
    <div id='div_pt6_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt6_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt6_1'>通过</button>
    <div id='div_pt6_1' class="collapse in">
    <pre>
    
pt6_1: 商标名称填写成功!
选择了第45类商标分类
申请人信息填写成功!
订单提交成功，应付金额:321.00


    </pre>
    </div>
    </td>
</tr>

<tr id='pt6_2' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_hhrsbzc: 合伙人商标注册</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt6_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt6_2'>通过</button>
    <div id='div_pt6_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt6_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt6_2'>通过</button>
    <div id='div_pt6_2' class="collapse in">
    <pre>
    
pt6_2: 商标名称填写成功!
选择了第40类商标分类
总价:600.00
申请人信息填写成功!
联系人信息填写成功!
订单提交成功，应付金额:600.00
价格一致
合伙人订单下单成功!
订单已发送客户付款!


    </pre>
    </div>
    </td>
</tr>

<tr id='ft6_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_sbdd: 商标订单</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft6_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft6_3'>错误</button>
    <div id='div_ft6_3' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft6_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft6_3'>错误</button>
    <div id='div_ft6_3' class="collapse in">
    <pre>
    
ft6_3: 商标名字修改成功
Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\hhrtest.py", line 71, in test_sbdd
    self.driver.find_element_by_css_selector("#edit-category &gt; div.modal-button &gt; a.button.save").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element &lt;a href="javascript:void(0)" class="button save"&gt;...&lt;/a&gt; is not clickable at point (937, 624). Other element would receive the click: &lt;div class="clearfix"&gt;&lt;/div&gt;
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>hometest.hometest: 个人中心测试集</td>
    <td class="text-center">4</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">3</td>
    <td class="text-center"><a href="javascript:showClassDetail('c7',4)" class="detail" id='c7'>详细</a></td>
</tr>

<tr id='ft7_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_ddzx: 订单中心</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft7_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft7_1'>错误</button>
    <div id='div_ft7_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft7_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft7_1'>错误</button>
    <div id='div_ft7_1' class="collapse in">
    <pre>
    
ft7_1: 权大师_我的商标
Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\hometest.py", line 45, in test_ddzx
    self.driver.find_element_by_css_selector("#personalCenter2-rightContainer &gt; div.order-detail-page &gt; div:nth-child(4) &gt; h2 &gt; a").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 437, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#personalCenter2-rightContainer &gt; div.order-detail-page &gt; div:nth-child(4) &gt; h2 &gt; a"}
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='pt7_2' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_dzgl: 发票地址管理</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt7_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt7_2'>通过</button>
    <div id='div_pt7_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt7_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt7_2'>通过</button>
    <div id='div_pt7_2' class="collapse in">
    <pre>
    
pt7_2: 权大师_邮寄地址管理
添加邮寄地址成功！
测试通过！


    </pre>
    </div>
    </td>
</tr>

<tr id='ft7_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_fpsq: 发票申请</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft7_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft7_3'>错误</button>
    <div id='div_ft7_3' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft7_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft7_3'>错误</button>
    <div id='div_ft7_3' class="collapse in">
    <pre>
    
ft7_3: 权大师_我的发票申请
Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\hometest.py", line 178, in test_fpsq
    self.driver.find_element_by_css_selector("#personalCenter2-rightContainer &gt; div.order-page.p-invoice-content &gt; div.tabsPanel &gt; div &gt; div.section1 &gt; table &gt; tbody &gt; tr &gt; td:nth-child(8) &gt; div &gt; a").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 437, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#personalCenter2-rightContainer &gt; div.order-page.p-invoice-content &gt; div.tabsPanel &gt; div &gt; div.section1 &gt; table &gt; tbody &gt; tr &gt; td:nth-child(8) &gt; div &gt; a"}
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft7_4' class='none'>
    <td class='errorCase'><div class='testcase'>test_gwyj: 官文邮寄</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft7_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft7_4'>错误</button>
    <div id='div_ft7_4' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft7_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft7_4'>错误</button>
    <div id='div_ft7_4' class="collapse in">
    <pre>
    
ft7_4: 权大师_官文待申请
Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\hometest.py", line 231, in test_gwyj
    self.driver.find_element_by_css_selector("#personalCenter2-rightContainer &gt; div.cho-wrap-wrap &gt; div &gt; dl &gt; dd.next-btn").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>hwgstest.hwgstest: 海外高速测试集</td>
    <td class="text-center">2</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">1</td>
    <td class="text-center"><a href="javascript:showClassDetail('c8',2)" class="detail" id='c8'>详细</a></td>
</tr>

<tr id='pt8_1' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_hwgs_1: 海外高速测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt8_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt8_1'>通过</button>
    <div id='div_pt8_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt8_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt8_1'>通过</button>
    <div id='div_pt8_1' class="collapse in">
    <pre>
    
pt8_1: 商标注册-权大师
费用总计:600.00
总价:600.00
价格一致
订单提交成功，应付金额:600.00
测试通过


    </pre>
    </div>
    </td>
</tr>

<tr id='ft8_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_hwgs_2: 海外高速_自然人测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft8_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft8_2'>错误</button>
    <div id='div_ft8_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft8_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft8_2'>错误</button>
    <div id='div_ft8_2' class="collapse in">
    <pre>
    
ft8_2: 商标注册-权大师
费用总计:600.00
总价:600.00
价格一致
Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\hwgstest.py", line 245, in test_hwgs_2
    self.assertIn(oo,ii)
UnboundLocalError: local variable 'oo' referenced before assignment


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>hwsctest.sbzrtest: 海外市场测试集</td>
    <td class="text-center">6</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">6</td>
    <td class="text-center"><a href="javascript:showClassDetail('c9',6)" class="detail" id='c9'>详细</a></td>
</tr>

<tr id='ft9_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_mdl: 马德里商标注册测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft9_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft9_1'>错误</button>
    <div id='div_ft9_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft9_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft9_1'>错误</button>
    <div id='div_ft9_1' class="collapse in">
    <pre>
    
ft9_1: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\hwsctest.py", line 30, in test_mdl
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(1) &gt; div &gt; dl:nth-child(7) &gt; dd &gt; a:nth-child(1)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft9_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_mg: 美国商标注册测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft9_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft9_2'>错误</button>
    <div id='div_ft9_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft9_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft9_2'>错误</button>
    <div id='div_ft9_2' class="collapse in">
    <pre>
    
ft9_2: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\hwsctest.py", line 87, in test_mg
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(1) &gt; div &gt; dl:nth-child(7) &gt; dd &gt; a:nth-child(2)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft9_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_om: 欧盟商标注册测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft9_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft9_3'>错误</button>
    <div id='div_ft9_3' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft9_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft9_3'>错误</button>
    <div id='div_ft9_3' class="collapse in">
    <pre>
    
ft9_3: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\hwsctest.py", line 143, in test_om
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(1) &gt; div &gt; dl:nth-child(7) &gt; dd &gt; a:nth-child(3)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft9_4' class='none'>
    <td class='errorCase'><div class='testcase'>test_rb: 日本商标注册测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft9_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft9_4'>错误</button>
    <div id='div_ft9_4' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft9_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft9_4'>错误</button>
    <div id='div_ft9_4' class="collapse in">
    <pre>
    
ft9_4: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\hwsctest.py", line 200, in test_rb
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(1) &gt; div &gt; dl:nth-child(7) &gt; dd &gt; a:nth-child(4)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft9_5' class='none'>
    <td class='errorCase'><div class='testcase'>test_xg: 香港商标注册测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft9_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft9_5'>错误</button>
    <div id='div_ft9_5' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft9_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft9_5'>错误</button>
    <div id='div_ft9_5' class="collapse in">
    <pre>
    
ft9_5: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\hwsctest.py", line 314, in test_xg
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(1) &gt; div &gt; dl:nth-child(7) &gt; dd &gt; a:nth-child(6)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft9_6' class='none'>
    <td class='errorCase'><div class='testcase'>test_yd: 印度商标注册测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft9_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft9_6'>错误</button>
    <div id='div_ft9_6' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft9_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft9_6'>错误</button>
    <div id='div_ft9_6' class="collapse in">
    <pre>
    
ft9_6: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\hwsctest.py", line 257, in test_yd
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(1) &gt; div &gt; dl:nth-child(7) &gt; dd &gt; a:nth-child(5)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr class='failClass warning'>
    <td>mfsbtest.gnsbtest: 商标搜索查询测试集</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c10',1)" class="detail" id='c10'>详细</a></td>
</tr>

<tr id='ft10_1' class='none'>
    <td class='failCase'><div class='testcase'>test_sbss: 商标搜索</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft10_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft10_1'>失败</button>
    <div id='div_ft10_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft10_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft10_1'>失败</button>
    <div id='div_ft10_1' class="collapse in">
    <pre>
    
ft10_1: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\mfsbtest.py", line 48, in test_sbss
    self.assertIn("测试_全球更好用的商标搜索_权大师",self.driver.title)
AssertionError: '测试_全球更好用的商标搜索_权大师' not found in '商标查询|免费商标查询|商标注册-权大师官网'


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>rjzztest.rjzztest: 软件著作权测试集</td>
    <td class="text-center">2</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">2</td>
    <td class="text-center"><a href="javascript:showClassDetail('c11',2)" class="detail" id='c11'>详细</a></td>
</tr>

<tr id='ft11_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_rjzz: 软件著作权登记</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft11_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft11_1'>错误</button>
    <div id='div_ft11_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft11_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft11_1'>错误</button>
    <div id='div_ft11_1' class="collapse in">
    <pre>
    
ft11_1: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\rjzztest.py", line 34, in test_rjzz
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(3) &gt; div &gt; dl:nth-child(1) &gt; dd &gt; a:nth-child(1)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft11_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_rjzz_j: 软件著作权登记加急</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft11_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft11_2'>错误</button>
    <div id='div_ft11_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft11_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft11_2'>错误</button>
    <div id='div_ft11_2' class="collapse in">
    <pre>
    
ft11_2: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\rjzztest.py", line 94, in test_rjzz_j
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(3) &gt; div &gt; dl:nth-child(1) &gt; dd &gt; a:nth-child(2)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>sbxxtest.sbxxtest: 商标信息测试集</td>
    <td class="text-center">5</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">5</td>
    <td class="text-center"><a href="javascript:showClassDetail('c12',5)" class="detail" id='c12'>详细</a></td>
</tr>

<tr id='ft12_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_sbbg: 商标变更测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft12_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft12_1'>错误</button>
    <div id='div_ft12_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft12_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft12_1'>错误</button>
    <div id='div_ft12_1' class="collapse in">
    <pre>
    
ft12_1: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\sbxxtest.py", line 260, in test_sbbg
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(1) &gt; div &gt; dl:nth-child(6) &gt; dd &gt; a:nth-child(5)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft12_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_sbkz: 商标宽展测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft12_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft12_2'>错误</button>
    <div id='div_ft12_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft12_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft12_2'>错误</button>
    <div id='div_ft12_2' class="collapse in">
    <pre>
    
ft12_2: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\sbxxtest.py", line 146, in test_sbkz
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(1) &gt; div &gt; dl:nth-child(6) &gt; dd &gt; a:nth-child(3)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft12_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_sbxk: 商标许可备案测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft12_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft12_3'>错误</button>
    <div id='div_ft12_3' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft12_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft12_3'>错误</button>
    <div id='div_ft12_3' class="collapse in">
    <pre>
    
ft12_3: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\sbxxtest.py", line 203, in test_sbxk
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(1) &gt; div &gt; dl:nth-child(6) &gt; dd &gt; a:nth-child(4)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft12_4' class='none'>
    <td class='errorCase'><div class='testcase'>test_sbxz: 商标续展让测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft12_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft12_4'>错误</button>
    <div id='div_ft12_4' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft12_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft12_4'>错误</button>
    <div id='div_ft12_4' class="collapse in">
    <pre>
    
ft12_4: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\sbxxtest.py", line 89, in test_sbxz
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(1) &gt; div &gt; dl:nth-child(6) &gt; dd &gt; a:nth-child(2)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft12_5' class='none'>
    <td class='errorCase'><div class='testcase'>test_sbzr: 商标转让测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft12_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft12_5'>错误</button>
    <div id='div_ft12_5' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft12_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft12_5'>错误</button>
    <div id='div_ft12_5' class="collapse in">
    <pre>
    
ft12_5: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\sbxxtest.py", line 32, in test_sbzr
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(1) &gt; div &gt; dl:nth-child(6) &gt; dd &gt; a:nth-child(1)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>yytrtest.yytrtest: 异议他人商标测试集</td>
    <td class="text-center">3</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">3</td>
    <td class="text-center"><a href="javascript:showClassDetail('c13',3)" class="detail" id='c13'>详细</a></td>
</tr>

<tr id='ft13_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_sbcs: 商标撤三测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft13_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft13_1'>错误</button>
    <div id='div_ft13_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft13_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft13_1'>错误</button>
    <div id='div_ft13_1' class="collapse in">
    <pre>
    
ft13_1: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\yytrtest.py", line 30, in test_sbcs
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(1) &gt; div &gt; dl:nth-child(5) &gt; dd &gt; a:nth-child(1)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft13_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_sbwx: 商标无效宣告申请测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft13_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft13_2'>错误</button>
    <div id='div_ft13_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft13_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft13_2'>错误</button>
    <div id='div_ft13_2' class="collapse in">
    <pre>
    
ft13_2: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\yytrtest.py", line 142, in test_sbwx
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(1) &gt; div &gt; dl:nth-child(5) &gt; dd &gt; a:nth-child(3)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft13_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_sbyy: 商标异议申请测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft13_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft13_3'>错误</button>
    <div id='div_ft13_3' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft13_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft13_3'>错误</button>
    <div id='div_ft13_3' class="collapse in">
    <pre>
    
ft13_3: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\yytrtest.py", line 86, in test_sbyy
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(1) &gt; div &gt; dl:nth-child(5) &gt; dd &gt; a:nth-child(2)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>zahjtest.zahjtest: 遇到障碍如何化解测试集</td>
    <td class="text-center">3</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">3</td>
    <td class="text-center"><a href="javascript:showClassDetail('c14',3)" class="detail" id='c14'>详细</a></td>
</tr>

<tr id='ft14_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_sbbh: 商标驳回测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft14_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft14_1'>错误</button>
    <div id='div_ft14_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft14_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft14_1'>错误</button>
    <div id='div_ft14_1' class="collapse in">
    <pre>
    
ft14_1: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\zahjtest.py", line 30, in test_sbbh
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(1) &gt; div &gt; dl:nth-child(4) &gt; dd &gt; a:nth-child(1)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft14_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_sbcsdb: 商标撤三答辩测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft14_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft14_2'>错误</button>
    <div id='div_ft14_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft14_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft14_2'>错误</button>
    <div id='div_ft14_2' class="collapse in">
    <pre>
    
ft14_2: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\zahjtest.py", line 142, in test_sbcsdb
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(1) &gt; div &gt; dl:nth-child(4) &gt; dd &gt; a:nth-child(3)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft14_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_sbdb: 商标异议答辩测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft14_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft14_3'>错误</button>
    <div id='div_ft14_3' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft14_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft14_3'>错误</button>
    <div id='div_ft14_3' class="collapse in">
    <pre>
    
ft14_3: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\zahjtest.py", line 86, in test_sbdb
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(1) &gt; div &gt; dl:nth-child(4) &gt; dd &gt; a:nth-child(2)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>zlywtest.zlywtest: 专利业务测试集</td>
    <td class="text-center">10</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">10</td>
    <td class="text-center"><a href="javascript:showClassDetail('c15',10)" class="detail" id='c15'>详细</a></td>
</tr>

<tr id='ft15_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_cpwg: 产品外观设计测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft15_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft15_1'>错误</button>
    <div id='div_ft15_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft15_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft15_1'>错误</button>
    <div id='div_ft15_1' class="collapse in">
    <pre>
    
ft15_1: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\zlywtest.py", line 89, in test_cpwg
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(2) &gt; div &gt; dl:nth-child(3) &gt; dd &gt; a:nth-child(1)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft15_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_gui: GUI外观设计测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft15_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft15_2'>错误</button>
    <div id='div_ft15_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft15_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft15_2'>错误</button>
    <div id='div_ft15_2' class="collapse in">
    <pre>
    
ft15_2: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\zlywtest.py", line 146, in test_gui
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(2) &gt; div &gt; dl:nth-child(3) &gt; dd &gt; a:nth-child(2)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft15_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_nfjn: 年费缴纳测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft15_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft15_3'>错误</button>
    <div id='div_ft15_3' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft15_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft15_3'>错误</button>
    <div id='div_ft15_3' class="collapse in">
    <pre>
    
ft15_3: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\zlywtest.py", line 485, in test_nfjn
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(2) &gt; div &gt; dl:nth-child(6) &gt; dd &gt; a:nth-child(1)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft15_4' class='none'>
    <td class='errorCase'><div class='testcase'>test_syxxjc: 实用新型专利基础版</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft15_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft15_4'>错误</button>
    <div id='div_ft15_4' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft15_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft15_4'>错误</button>
    <div id='div_ft15_4' class="collapse in">
    <pre>
    
ft15_4: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\zlywtest.py", line 202, in test_syxxjc
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(2) &gt; div &gt; dl:nth-child(4) &gt; dd &gt; a:nth-child(1)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft15_5' class='none'>
    <td class='errorCase'><div class='testcase'>test_syxxzl: 实用新型专利卓越版</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft15_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft15_5'>错误</button>
    <div id='div_ft15_5' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft15_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft15_5'>错误</button>
    <div id='div_ft15_5' class="collapse in">
    <pre>
    
ft15_5: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\zlywtest.py", line 259, in test_syxxzl
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(2) &gt; div &gt; dl:nth-child(4) &gt; dd &gt; a:nth-child(2)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft15_6' class='none'>
    <td class='errorCase'><div class='testcase'>test_zlbg: 专利著录项变更测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft15_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft15_6'>错误</button>
    <div id='div_ft15_6' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft15_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft15_6'>错误</button>
    <div id='div_ft15_6' class="collapse in">
    <pre>
    
ft15_6: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\zlywtest.py", line 542, in test_zlbg
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(2) &gt; div &gt; dl:nth-child(6) &gt; dd &gt; a:nth-child(2)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft15_7' class='none'>
    <td class='errorCase'><div class='testcase'>test_zlbh: 专利驳回复审测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft15_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft15_7'>错误</button>
    <div id='div_ft15_7' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft15_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft15_7'>错误</button>
    <div id='div_ft15_7' class="collapse in">
    <pre>
    
ft15_7: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\zlywtest.py", line 316, in test_zlbh
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(2) &gt; div &gt; dl:nth-child(5) &gt; dd &gt; a:nth-child(1)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft15_8' class='none'>
    <td class='errorCase'><div class='testcase'>test_zldb: 专利无效答辩测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft15_8' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft15_8'>错误</button>
    <div id='div_ft15_8' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft15_8' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft15_8'>错误</button>
    <div id='div_ft15_8' class="collapse in">
    <pre>
    
ft15_8: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\zlywtest.py", line 429, in test_zldb
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(2) &gt; div &gt; dl:nth-child(5) &gt; dd &gt; a:nth-child(3)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft15_9' class='none'>
    <td class='errorCase'><div class='testcase'>test_zljs: 专利查新检索（报告）测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft15_9' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft15_9'>错误</button>
    <div id='div_ft15_9' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft15_9' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft15_9'>错误</button>
    <div id='div_ft15_9' class="collapse in">
    <pre>
    
ft15_9: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\zlywtest.py", line 30, in test_zljs
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(2) &gt; div &gt; dl:nth-child(1) &gt; dd &gt; a").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft15_10' class='none'>
    <td class='errorCase'><div class='testcase'>test_zlxg: 专利无效宣告测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft15_10' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft15_10'>错误</button>
    <div id='div_ft15_10' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft15_10' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft15_10'>错误</button>
    <div id='div_ft15_10' class="collapse in">
    <pre>
    
ft15_10: Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\zlywtest.py", line 372, in test_zlxg
    "body &gt; div.section-banner &gt; div.public-navbar &gt; div &gt; div &gt; div &gt; ul:nth-child(1) &gt; li:nth-child(2) &gt; div &gt; dl:nth-child(5) &gt; dd &gt; a:nth-child(2)").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>znzztest.znzztest: 智能注册测试集</td>
    <td class="text-center">2</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">2</td>
    <td class="text-center"><a href="javascript:showClassDetail('c16',2)" class="detail" id='c16'>详细</a></td>
</tr>

<tr id='ft16_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_znzz_1: 智能注册_企业测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft16_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft16_1'>错误</button>
    <div id='div_ft16_1' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft16_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft16_1'>错误</button>
    <div id='div_ft16_1' class="collapse in">
    <pre>
    
ft16_1: 商标注册-权大师
费用总计:300.00
选择了第2类商标分类!
Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\znzztest.py", line 121, in test_znzz_1
    self.driver.find_element_by_css_selector("body &gt; div.smartRegister-page &gt; div.agentInfo-wrap.applicant-wrap &gt; div.section-base &gt; div.applicant-form &gt; h2").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element &lt;h2 class="order-title"&gt;...&lt;/h2&gt; is not clickable at point (485, 83). Other element would receive the click: &lt;input type="text" class="search-key" placeholder="请输入商标名称关键字" id="qds-searchkey"&gt;
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='ft16_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_znzz_2: 智能注册_个体测试</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft16_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft16_2'>错误</button>
    <div id='div_ft16_2' class="collapse">  -->

    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft16_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft16_2'>错误</button>
    <div id='div_ft16_2' class="collapse in">
    <pre>
    
ft16_2: 商标注册-权大师
费用总计:300.00
选择了第2类商标分类!
Traceback (most recent call last):
  File "G:\quandashitest_company\quandashitest_company\case\znzztest.py", line 252, in test_znzz_2
    self.driver.find_element_by_css_selector("body &gt; div.smartRegister-page &gt; div.agentInfo-wrap.applicant-wrap &gt; div.section-base.open &gt; div.applicant-form &gt; h2").click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 494, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element &lt;h2 class="order-title"&gt;...&lt;/h2&gt; is not clickable at point (485, 127). Other element would receive the click: &lt;form action="" method="post" id="formFile"&gt;...&lt;/form&gt;
  (Session info: chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)



    </pre>
    </div>
    </td>
</tr>

<tr id='total_row' class="text-center active">
    <td>总计</td>
    <td>55</td>
    <td>6</td>
    <td>1</td>
    <td>48</td>
    <td>通过率：10.91%</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>
    <div style=" position:fixed;right:50px; bottom:30px; width:20px; height:20px;cursor:pointer">
    <a href="#"><span class="glyphicon glyphicon-eject" style = "font-size:30px;" aria-hidden="true">
    </span></a></div>
    

</body>
</html>
